= Compatibility of Couchbase Features, Couchbase Versions and the Couchbase Node.js SDK
:navtitle: Compatibility

[abstract]
Compatibility Information for the Couchbase Node.js SDK

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments, to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Node.js SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Couchbase Node.js SDK and Couchbase Server Compatibility Version Matrix
[#table_sdk_versions]
|===
| _CB/SDK_ | *SDK 2.0* | *SDK 2.1 - SDK 2.3* | *SDK 2.4*

| *CB 3.1*
| *◎*
| *✔*
| *✔*

| *CB 4.0 - 4.6*
| *✔*
| *✔*
| *✔*

| *CB 5.0 - 5.1*
| *✖*
| *✔*
| *✔*
|===

== Couchbase Feature Availability Matrix

.Couchbase Node.js SDK and Couchbase Server Feature Availability Matrix
|===
| Server → | 2.0 | 2.5 | 3.0 | 3.1 | 4.0 | 4.1 | 4.5 | 4.6 | 5.0

10+| *Basic Features*

| CRUD Operations
9+| Node.js SDK 2.0

| View Querying APIs
9+| Node.js SDK 2.0

| Geospatial Views
3+| Not Supported
6+| Since Node.js SDK 2.0

10+| *Advanced Features*

| Durability Requirements
9+| Node.js SDK 2.0

| Carrier Publication Configuration
2+| Not Supported
7+| Since Node.js SDK 2.0

| SSL Connectivity
3+| Not Supported
6+| Since Node.js SDK 2.0

| Bulk Operations
9+| NOT SUPPORTED IN NODEJS, except for Bulk "Get" Since Node.js SDK 2.0

| N1QL Querying
4+| Not Supported
5+| Since Node.js SDK 2.0

| Multi-Dimensional Scaling
4+| Not Supported
5+| Since Node.js SDK 2.1

| Sub-document API
6+| Not Supported
3+| Since Node.js SDK 2.2

| Fulltext Search
6+| Not Supported
3+| Since Node.js SDK 2.2

| Extended Attributes
8+| Not Supported
| Since Node.js SDK 2.3.3

10+| *Administrative Features*

| Administrative API
9+| Since Node.js SDK 2.0

| RBAC
8+| Not Supported
| Since Node.js SDK 2.3.3
|===

== Couchbase Node.js SDK Version 1.0

Version 1.0 of the Couchbase Node.js SDK is no longer supported.
It is recommended if you are still using this version to upgrade as soon as possible to the latest version of the SDK.
See the http://www.couchbase.com/support-policy[Couchbase Support Policy^] for details.

include::6.0@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
