= Data Structures

[abstract]
You can use complex data structures such as dictionaries and lists in Couchbase.
These data structures may be manipulated with basic operations without retrieving and storing the entire document.

Data structures in Couchbase are similar in concept to data structures in JavaScript:

* *Map* is like a JavaScript `Object`, and is a key-value structure, where a value is accessed by using a key string.
* *List* is like a JavaScript `array` and is a sequential data structure.
Values can be placed in the beginning or end of a list, and can be accessed using numeric indexes.
* *Set* is a wrapper over a _list_ which provides the ability to handle unique values.

These data structures are stored as JSON documents in Couchbase, and can therefore be accessed using N1QL, Full Text Search, and normal key-value operations.
Data structures can also be manipulated using the traditional sub-document and full-document KV APIs.

Using the data structures API may help your application in two ways:

* *Simplicity*: Data structures provide high level operations by which you can deal with documents as if they were container data structures.
Adding an item to a dictionary is expressed as `mapAdd`, rather than retrieving the entire document, modifying it locally, and then saving it back to the server.
* *Efficiency*: Data structure operations do not transfer the entire document across the network.
Only the relevant data is exchanged between client and server, allowing for less network overhead and lower latency.

== Creating a Data Structure

Data structures can be created implicitly by adding a `create: true` to the options of the operation.
For example, to add an item to a map, specify the _document ID_ of the map itself (i.e.
the ID which uniquely identifies the map in the server), the key _within_ the map, and the value to store under the key:

[source,javascript]
----
bucket.mapAdd('map_id', 'name', 'Mark Nunberg', {create: true}, function(err, result) {});
----

Likewise, to create a list, specify the document ID and the value to add:

[source,javascript]
----
bucket.listPush('list_id', 'hello', {create: true}, function(err, result) {});
----

Note that the `{create: true}` _will not_ overwrite an existing document with the same name if it already exists.
It is therefore always safe to use, unless your application creates data structures independently.

Data structures can be explicitly created and reset using full-document methods, and initialized with its JSON equivalent.
To create a new empty list or set, use `bucket.upsert('list_id', [])`.
To create an empty map, use `bucket.upsert('map_id', {})`.

== Accessing Data Structures

Data structures can be accessed using their appropriate methods.
You need to supply a callback that receives an error and a result object.
The actual returned value is can be accessed using the [.var]`result.value` property.

[source,javascript]
----
bucket.listGet('list_id', 0, function(err, result) {
    console.log('%s', result.value);
});
// Prints 'hello'
----

[source,javascript]
----
bucket.mapGet('map_id', 'name', function(err, result) {
    console.log('%s', result.value);
});
// Prints 'Mark Nunberg'
----

Here is a list of common operations:

.Data Structure Operations
[cols="25,94"]
|===
| |

| [.api]`mapRemove`
a|
Remove a key from a map.

[source,javascript]
----
bucket.mapRemove('map_id', 'some_key', function(err, result){});
----

| [.api]`mapGet`
a|
Get an item from a map.

[source,javascript]
----
bucket.mapGet('map_id', 'some_key', function(err, result) {
    console.log(result.value);
});
----

| [.api]`listPush`
a|
Add an item to the _end_ of a list.

[source,javascript]
----
bucket.listPush('list_id', 'some_value', function(err, result(){});
----

| [.api]`listShift`
a|
Add an item to the _beginning_ of a list.

[source,javascript]
----
bucket.listShift('list_id', 'some_value', function(err, result(){});
----

| [.api]`listGet`
a|
Get an item from a list by its index.

[source,javascript]
----
bucket.listGet('list_id', 1, function(err, result) {
    console.log(result.value);
});
----

| [.api]`setAdd`
a|
Add an item to a set, if the item does not yet exist in the set.

[source,javascript]
----
bucket.setAdd('list_id', 'some_value', function(err, result) {});
----

Note that a _set_ is just a list.
You can retrieve the entire set by simply using a full-document [.api]`get` operation:

[source,javascript]
----
bucket.get('list_id', function(err, result) {
    result.value; // <- this is the set
});
----

NOTE: Currently, using the node.js SDK you can only store primitive values in sets, such as strings, ints, and booleans.

| [.api]`setRemove`
a|
Remove an item from a set, if it exists.
An exception is not thrown if the item does not exist.
You can determine if an item existed or not by the return value.
If the item did not exist beforehand, `None` is returned.

[source,javascript]
----
bucket.setRemove('list_id', 'some_value', function(err, result){});
----

| [.api]`mapSize`, [.api]`listSize`, [.api]`setSize`
a|
These methods get the length of the data structure.
For maps, this is the number of key-value pairs inside the map.
For lists, and sets, this is the number of elements in the structure.

[source,javascript]
----
bucket.listSize('list_id', function(err, result) {
    console.log(result.value);
});
----
|===

Note that there are only *two* basic types: map and list.
Types such as _set_ are merely derivatives of _list_.

== Data Structures and Key-Value APIs

Data structures can be accessed using key-value APIs as well.
In fact, the data structure API is actually a client-side wrapper _around_ the key-value and sub-document API.
Most of the data structure APIs wrap the sub-document API directly.
Therefore, for example, the [.api]`map_set` can be implemented as follows:

[source,javascript]
----
function mapSet(bucket, docid, key, value, callback) {
    bucket.mutateIn(docid).upsert(key, value).execute(function(err, frag) {
        if (err) {
            callback(err);
        }
        callback(null, {value: frag.contentByIndex(0)});
    });
}
----

Some data structure operations are compound operations.
This means that they do not correspond to a single server-side operation.
For example, [.api]`setRemove` does not exist on the server.
In order to implement [.api]`setRemove`, it would require an implementation like so:

[source,javascript]
----
function setRemove(bucket, docid, value, callback) {
    bucket.get(docid, function(err, result) {
        if (err) {
            callback(err);
        } else {
            // Find the index
            value_index = err.result.indexOf(value);
            if (value_index != -1) {
                bucket.mutateIn(docid, {cas: result.cas}).remove('[' + value_index + ']').execute(function(err, res) {
                    callback(err, res);
                });
            }
        }
    });
}
----

In the example above, the entire document is fetched and the index of the value is retrieved.
If the value exists, the index of the value is removed at the server side.

NOTE: Because the data structure API is just a wrapper around the various key-value APIs, you are free to switch between them in your application code.
