= CRUD Document Operations using the Node.js SDK with Couchbase Server
:navtitle: Document Operations
:page-aliases: documents-creating,documents-updating,documents-retrieving,documents-deleting,howtos:kv-operations

You can access documents in Couchbase using the [.api]`Bucket` class (constructed via `cluster.openBucket()`).
You can retrieve documents using the [.api]`get()` and [.api]`lookupIn` methods, and mutate documents using the [.api]`upsert()`, [.api]`insert()`, [.api]`replace()`, and [.api]`mutateIn()` methods.

== Document Input Types

Documents can be anything convertible to JSON (`JSON.stringify`).
Simply pass the object or array to the mutation operation, and the SDK will convert it to JSON and store it on the server.
Do not pass already-serialized JSON to the SDK, as the SDK will serialize it again.

== Callbacks for operations

Due to the non-blocking nature of the node.js SDK and node.js in general, the results of all operations are signalled by callbacks.
Callbacks are specified as the last parameter to any operation.
The callback signature is generally

[source,javascript]
----
function(err, result) {
    if (err) {
        console.error("Got error!: %j", err);
    } else {
        console.log("Got result: %j", result);
    }
}
----

== Additional Options

Additional options may be passed to some methods using an object.

_Mutation_ operations ([.api]`upsert`, [.api]`insert`, [.api]`replace`, [.api]`mutate_in`) operations also accept a xref:core-operations.adoc#expiry[TTL (expiry)] value ([.param]`expiry`) which will instruct the server to delete the document after a given amount of time.
This option is useful for transient data (such as sessions).
By default documents do not expire.
See xref:core-operations.adoc#expiry[Expiration Overview] for more information on expiration.

Some mutation operations can also accept a xref:concurrent-mutations-cluster.adoc[CAS] ([.param]`cas`) value to protect against concurrent updates to the same document.
See xref:concurrent-mutations-cluster.adoc[CAS] for a description on how to use CAS values in your application.
Note that the CAS value is represented internally as `Buffer`.

== Creating and updating full documents

Documents may be created and updated using the [.api]`Bucket.upsert()`, [.api]`Bucket.insert()`, and [.api]`Bucket.replace()` family of methods.
Read more about the difference between these methods at xref:core-operations.adoc#crud-overview[Primitive Key-Value Operations] in the Couchbase developer guide.

These methods accept two mandatory arguments:

* [.param]`key`: The ID of the document to modify.
This should be a string.
* [.param]`value`: The desired new value of the document.
This may be anything that can be serialized as JSON.

Additional options can be specified in the options:

* [.param]`cas`: The CAS value for the document.
If the CAS on the server does not match the CAS supplied to the method, the operation will fail with a [.api]`couchbase.exceptions.KeyExistsError` error.
See xref:concurrent-mutations-cluster.adoc[Concurrent Document Mutations] for more information on the usage of CAS values.
* [.param]`expiry`: Specify the expiry time for the document.
If specified, the document will expire and no longer exist after the given number of seconds.
See xref:core-operations.adoc#expiry[Expiration Overview] for more information.
* [.param]`persist_to`, [.param]`replicate_to`: Specify xref:durability.adoc[durability requirements] for the operations.

When the operation is complete the callback will be invoked, and if successful, the `result` (the second callback argument) will contain the new xref:concurrent-mutations-cluster.adoc[CAS] value of the document.
If the document was not mutated successfully, the callback's first argument (`err`) will contain appropriate error information.
See xref:handling-error-conditions.adoc[Handling Exceptions and Other Errors with the Node.js SDK in Couchbase] for more information on error types and how to handle them.

[source,javascript]
----
bucket.insert('document_name', {'some': 'value'}, function(err, result) {
    if (!err) {
        console.log("stored document successfully. CAS is %j", result.cas);
    } else {
        console.error("Couldn't store document: %j", err);
    }
});
----

Output on success:

....
stored document successfully. CAS is "216000820675072"
....

....
Couldn't store document: {"message":"The key already exists in the server. If you have supplied a CAS then the key exists with a CAS value different than specified","code":12}
....

If the document being inserted already exists, the error will be set and its [.var]`code` field will be set to [.var]`couchbase.errors.keyAlreadyExists`.
If your application simply wants to set the value ignoring whether it exists or not, use the [.api]`upsert()` method.

== Retrieving full documents

Documents may be retrieved using the [.api]`Bucket.get()` method.
The [.api]`get()` method requires the document ID to retrieve, and the callback to invoke with the result of the operation.

When the operation is complete the callback is invoked.
If successful, you may access actual document may be access by using `result.value` and the CAS using `result.cas`.

The document will be a native javascript type resulting from the parsing of the stored server value.

Upon failure, the error (first callback argument) will be populate with an appropriate `code` and `message`.
If the document does not exist, the `code` will be [.var]`couchbase.errors.keyNotFound`

[source,javascript]
----
bucket.get('document_id', function(err, result) {
    if (err) {
        if (err.code == couchbase.errors.keyNotFound) {
            console.log('Key does not exist');
        } else {
            console.log('Some other error occurred: %j', err);
        }
    } else {
        console.log('Retrieved document with value: %j', result.value);
        console.log('CAS is %j', result.cas);
    }
});
----

Sample output:

....
Retrieved document with value: ["Hello","World"]
CAS is "166079006573056"
....

== Removing full documents

Documents may be removed using the [.api]`Bucket.remove()` method.
This method takes the document ID as a mandatory positional:

* [.param]`key`: The ID of the document to remove

Some additional options:

* [.param]`cas`: Only remove the document if the xref:concurrent-mutations-cluster.adoc[CAS] has not changed.

== Modifying expiraton

xref:core-operations.adoc#expiry[Document expiration] can be performed using the [.api]`Bucket.touch()` and [.api]`Bucket.getAndTouch` methods.
You can also set the [.param]`expiry` parameter for methods which support it:

.expiry with upsert
[source,javascript]
----
bucket.upsert('deleteMe', {'delete': 'me'}, {'expiry': 1}, function(err){
    bucket.get('deleteMe', function(err, result) {
        console.log('Have item: %j', result.value);
        console.log('Will attempt get later on..');
        setTimeout(function(){
            bucket.get('deleteMe', function(err, result){
                console.log('Got error: %s', err.message);
            })
        }, 3500);
    })
});
----

....
Have item: {"delete":"me"}
Will attempt get later on..
Got error: The key does not exist on the server
....

.Using getAndTouch
[source,javascript]
----
bucket.getAndTouch('some_document', 2, function(err, result) {
    console.log('Got value: %j', result.value);
    console.log('Will try again..');
    setTimeout(function(err, result){
        bucket.get('some_document', function(err, result) {
            console.error('Got error: %s', err.message);
        });
    }, 3000);
});
----

== Atomic document modifications

Additional atomic document modifications can be performed using the node.js SDK.
You can modify a xref:core-operations.adoc#devguide_kvcore_append_prepend_generic[counter document] using the [.api]`Bucket.counter()` method.
You can also use the [.api]`Bucket.append` and [.api]`Bucket.prepend` methods to perform raw byte concatenation.

== Batching Operations

All operations performed in the node.js SDK are inherently batched between event loop iterations.
In simple terms, this means that there is no added network performance for using any form of multi operation.

As a convenience, the node.js SDK provides an [.api]`Bucket.getMulti` which accepts multiple keys and returns their results.

== Operating with sub-documents

TIP: Sub-Document API is available starting Couchbase Server version 4.5.
See xref:subdocument-operations.adoc[Sub-Document Operations] for an overview.

Sub-document operations save network bandwidth by allowing you to specify _paths_ of a document to be retrieved or updated.
The document is parsed on the server and only the relevant sections (indicated by _paths_) are transferred between client and server.
You can execute xref:subdocument-operations.adoc[sub-document] operations in the node.js SDK using the [.api]`Bucket.mutateIn`, and [.api]`Bucket.lookupIn` methods.

Each of these methods accepts a [.param]`key` as its mandatory first argument and returns a builder object which can be used to add one or more _command specifications_ specifying an operation and a document field operand.
To submit the operation, invoke the [.api]`execute()` method on the builder, passing it the callback to be invoked.

[source,javascript]
----
bucket.lookupIn('some_document').
    get('path.to.get').
    exists('check.path.exists').
    execute(function(err, fragment) {
    // ...
});
----

The callback function is invoked with an `error` and a `fragment`.
The fragment is a [.api]`DocumentFragment` object containing the fragments of the document (corresponding to each path).
In contrast with a normal callback which returns a single error and result, each operation in the builder has its own result and status.
You can use `fragment.contentByIndex` or `fragment.content(path)` or `fragment.contentByIndex(index)` to retrieve the result for an individual path/command.
If a path has an error, the SDK will throw an exception.

Unlike other operations as well, both the `error` and `fragment` can be set.
If the `error` is set, and `error.code` is [.var]`couchbase.errors.checkResults` then it means that at least one command has failed.
If the top-level error code is something else, it means that the document itself could not be accessed.

[source,javascript]
----
bucket.lookupIn('some_document').
    get('path.to.get').
    exists('check.path.exists').
    execute(function(err, result) {
    if (!err || err.code == couchbase.errors.checkResults) {
        for (var i = 0; i < 2; i++) {
            try {
                console.log('Result for path index %d: %j', i, result.contentByIndex(i));
            } catch (e) {
                console.error('Error for path index %d: %s', i, e.message);
            }
        }
    } else {
        console.error("Couldn't access document: %s", err.message);
    }
});
----

You can also mutate documents in a similar manner:

[source,javascript]
----
bucket.mutateIn('some_document').
    upsert('path.to.upsert', 'value', true).
    remove('path.to.del').
    execute(function(err, frag) {
    if (!err || err.code == couchbase.errors.checkResults) {
        for (var i = 0; i < 2; i++) {
            try {
                frag.contentByIndex(i);
            } catch (e) {
                console.error('Error for index %d: %s', i, e.message);
            }
        }
    } else {
        console.error('Top-level document error: %j', err)
    }
});
----

== Formats and Non-JSON Documents

TIP: See xref:nonjson.adoc[Non-JSON Documents] for a general overview of using non-JSON documents with Couchbase

All JavaScript types which can be represented as JSON may be passed unmodified to a storage function, and be received via the [.api]`get` method without any additional modifications.

You can implement a custom xref:nonjson.adoc[transcoder] if you would like to serialize documents to/from a format other than JSON, or if you would like to interact with other SDKs which use non-JSON serialization formats.
See [.api]`Bucket.setTranscoder()`.
