= Full Text Search (FTS) using the Node.js SDK with Couchbase Server
:navtitle: Searching from the SDK

[abstract]
Using the Node.js SDK, you can use the Couchbase Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.

Couchbase offers Full-text search support, allowing you to search for documents that contain certain words or phrases.
In the Node.js SDK you can search full-text indexes by using the [.api]`SearchQuery` object and executing it with the [.api]`Bucket.query()` API.

include::4.5@sdk:shared:partial$experimental-pars.adoc[tag=fts]

The following example shows how to send a simple Search query:

[source,javascript]
----
var SearchQuery = couchbase.SearchQuery;
var query = SearchQuery.new('travel-search', SearchQuery.term('office'));
bucket.query(query, function(err, res, meta) {
  for (var i = 0; i < res.length; ++i) {
    console.log('Hit:', res[i].id);
  }
});
----

The [.api]`Bucket.query()` method returns a [.api]`SearchQueryResponse` object which provides access to all of the information returned by the query.

Other search result data may be accessed using the various other available methods on the [.api]`SearchResults` interface.

[source,javascript]
----
bucket.query(…, function(err, res, meta) {
  console.log('Total Hits:', meta.status.total);
  for (var i in meta.facets) {
    console.log('Facet:', i);
  }
});
----

== Query Types

Query types may be found within the `SearchQuery` class.
The package contains query classes corresponding to those enumerated in xref:4.5@server:fts:fts-query-types.adoc[Types of Queries].
The query object should be instantiated by using the associated function matching the type of query you wish to create (i.e.: `SearchQuery.term()` for a TermQuery), passing the search term (usually a string) as the first argument, followed by some query modifiers.

It is important to distinguish between _query options_ and general _search options_.
Some options affect the search process in general (such as the [.param]`Limit`, indicating how many results to return) while others only affect a specific query (such as [.param]`Fuzziness` for a given query).
Because multiple queries can be combined in a single search operation, _query specific options_ can be specified only in the query object itself, while _search options_ are specified through methods on the [.api]`SearchQuery` object itself.

== Query Facets

Query xref:full-text-search-overview.adoc#facets[facets] may also be added to the _general search parameters_ by using the [.param]`addFacet` method.
The [.param]`addFacet` method accepts a facet name as well as a facet definition You can create facets by instantiating a [.api]`Facet` object using methods found in the [.api]`SearchFacet` class (i.e.: `SearchFacet.term()` for a TermFacet).

[source,javascript]
----
var query = SearchQuery.new('travel-search', SearchQuery.term('office'));
query.addFacet('countries', SearchFacet.term('country', 5);
bucket.query(query, function(err, res, meta) {
  console.log('Total Countries:', meta.facets['countries'].total);
});
----
