= Managing Clusters using the Node SDK with Couchbase Server
:navtitle: Managing Clusters

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Node SDK also comes with some convenience functionality for common Couchbase management requests.

You can manage Couchbase clusters by using the `ClusterManager` and `BucketManager` interfaces that are available through the [.api]`manager(login, password)` and [.api]`manager()` methods exposed in `Cluster` and `Bucket` instances.

== Creating and removing buckets

Creating buckets and removing buckets is performed, for example,  when running unit tests.

The [.api]`ClusterManager` class may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the [.api]``Cluster``'s [.api]`manager()` method, providing the administrative username and password.

[source,javascript]
----
var clusterManager = cluster.manager("Administrator", "123456")
----

To create a bucket, use the [.api]`createBucket(name, opts, callback)` method.
The [.param]`opts` represents the options of the bucket, an object with the following structure (shown with default values):

[source,javascript]
----
var myOpts = {
  authType: 'sasl',
  bucketType: 'couchbase',
  ramQuotaMB: 100,
  replicaNumber: 1,
  saslPassword: null,
  flushEnabled: null
};
----

The parameters correspond to those in the REST API, most notably:

* [.param]`bucketType`: Defaults to `"couchbase"`, but can also be `"memcached"` to create a cache bucket.
* [.param]`ramQuotaMB`: How much memory should each node use for the bucket.
This number is specified in megabytes.
* [.param]`saslPassword`: If specified, makes this bucket password protected, forcing future connects (using the [.api]`Bucket`) to specify the [.param]`password` parameter.
Must be used together with the [.param]`authType: 'sasl'` (which is the default).
* [.param]`flushEnabled`: Enables the [.api]`BucketManager#flush()` operation to be performed on this bucket (see the <<node-flushing>> section below).
* [.param]`replicaNumber`: The number of replicas to use for the bucket.
* [.param]`replicaIndex`: Whether or not to replicate indexes.

The following example creates an "hello" bucket with only the [.param]`flushEnabled` differing from the defaults shown above:

[source,javascript]
----
var manager = cluster.manager("Administrator", "123456");
manager.createBucket("hello", { flushEnabled: true }, function(err) {
  console.log('Creation of hello bucket failed:', err);
});
----

// TODO does the Node SDK automatically wait for the bucket to be ready, or is there some polling involved?
// if polling, the shared content <p conref="../shared/flush-info-pars.dita#toplevel/after-creation"/> should be added

You can completely delete a bucket using the [.api]`removeBucket(name)` method:

[source,javascript]
----
manager.removeBucket("hello", function(err) {
  console.log('Could not delete hello bucket: ', err);
});
----

[#node-flushing]
== Flushing Buckets

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You may flush a bucket in the Node SDK by using the [.api]``BucketManager``'s [.api]`flush()` method:

[source,javascript]
----
var bucketMgr = bucket.manager();
bucketMgr.flush(function(err, status) {
  if (status) {
    console.log('Bucket flushed');
  } else {
    console.log('Could not flush bucket: ', err);
  }
});
----

The [.api]`flush` operation may notably fail if the bucket does not have flush enabled.

[#node-view-management]
== View Management

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

To create a view, you can use the `manager()` method of your bucket instance to retrieve a `BucketManager` instance.
After you have a `BucketManager` instance, invoke the `upsertDesignDocument` method to store the design document for later querying.

The following example creates or updates a "ddocname" design document with a single "by_name" view on the "hello" bucket (because it is created through hello's [.api]`BucketManager`):

[source,javascript]
----
var bucket = cluster.openBucket("hello");
var bucketMgr = bucket.manager();

var ddocdata = {
  views: {
    by_name: {
      map: [ 'function(doc, meta) {',
             '  if (doc.type && doc.type == "beer") {',
             '    emit(doc.name, null);',
             '  }',
             '}'
       ].join('\n')
     },
  }
};

bucketMgr.upsertDesignDocument('ddocname', ddocdata, function(err) {
  console.log('Insertion of design document completed with error:', err);
});
----

Alternatively, you can just pass a JavaScript function into the design document manipulation methods and they will automatically be serialized to JavaScript.
For instance, the following code snippets are functionally equivalent:

[source,javascript]
----
// Using a string
var ddocdata = {
  views: {
    by_name: {
      map: [ 'function(doc, meta) {',
             '  if (doc.type && doc.type == "beer") {',
             '    emit(doc.name, null);',
             '  }',
             '}'
      ].join('\n')
    },
  }
};

// Using a function
var ddocdata = {
  views: {
    by_name: {
      map: function(doc, meta) {
        if (doc.type && doc.type == "beer") {
          emit(doc.name, null);
        }
      }
    },
  }
};
----

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Here is an example of deleting a view from an existing document, which follows the same principle:

[source,javascript]
----
var bucket = cluster.openBucket();
var bucketMgr = bucket.manager();

function deleteView(ddocname, viewname, callback) {
  bucketMgr.getDesignDocument(ddocname, function(err, ddoc, meta) {
    if (err) {
      return callback(err);
    }

    //we have the current exhaustive list of views, delete the one we want to remove
    delete ddoc.views[viewname];

    //update the new exhaustive design document
    bucketMgr.upsertDesignDocument(ddocname, ddoc, function(err) {
      if (err) {
        return callback(err);
      }

      callback(null);
    });
  });
}

deleteView('ddoc', 'view', function(err) {
  console.log('Deletion completed with error:', err);
});
----

To remove a complete design document from a bucket, pass its name to the `removeDesignDocument` method.
