= Managing Connections Using the Node.js SDK with Couchbase Server
:navtitle: Managing Connections
:page-topic-type: concept

[abstract]
This section describes how to connect the Node.JS SDK to a Couchbase cluster and bucket.
It contains best practices as well as information on the connection string,  SSL and other advanced connection options.

You can specify additional options when connecting to the cluster by using the _connection string_.
The connection string indicates to the client where cluster nodes may be found and how to connect to them.
The _connection string_ is common to other Couchbase SDKs as well as the xref:webui-cli-access.adoc[command-line client].
The _connection string_ uses a URI-like format and is similar to a _DSN_ used in other database systems.

== Creating a Cluster Object

The [.api]`Cluster` object serves as an organizational unit for any [.api]`Bucket` objects created.
As on the server each bucket is a member of a cluster, likewise in the SDK each [.api]`Bucket` object is a child of a [.api]`Cluster`.
To create a cluster, construct it using a _connection string_, specifying the scheme and host(s) to connect to:

[source,javascript]
----
var couchbase = require('couchbase');
var cluster = new couchbase.Cluster('couchbase://10.0.0.1');
----

== Authenticating

From Couchbase Server 5.0, you will need to authenticate the user, rather than against the bucket, as part of xref:6.0@server:learn:security/authorization-overview.adoc[Role-Based Access Control].
You will need to use `cluster.authenticate`:

[source,nodejs]
----
cluster.authenticate('USERNAME', 'PASSWORD');
----

== Connecting to a Bucket

To connect to a bucket, invoke the [.api]`Cluster` object's [.api]`openBucket` call.
The [.api]`openBucket` method takes a bucket name as an argument.
If your bucket is protected by a password, pass it as the second parameter to [.api]`openBucket`.
[.api]`openBucket` also accepts a function as its final argument which reports any connection errors which may happen between the creation of the [.api]`Bucket` object and the actual connection.

[source,javascript]
----
var bucket = cluster.openBucket('protectedBucket', function(err) {
  if (err) {
    console.error('Got error: %j', err);
  }
});
----

== Disconnecting from a Bucket

If the [.api]`Bucket` object is no longer needed, you should call the [.api]`Bucket.disconnect()` function.
This will disconnect any existing TCP connections between the object and the server.

== Scalability and Concurrency

Creating a new [.api]`Bucket` object is relatively expensive, and keeping many idle [.api]`Bucket` objects will negatively impact server performance (if done at a large scale).
Typically your application will require only one [.api]`Bucket` instance per Couchbase bucket

include::2.8@c-sdk::page$managing-connections.adoc[tag=group]
