= Working with N1QL queries
:page-topic-type: concept

[abstract]
You can perform Couchbase Query Language (N1QL) queries via Couchnode.

To send N1QL queries, you must specify a list of application query hosts through the `enableN1ql` method (a temporary necessity).
After you have done this, you can perform a N1QL query by using the `query()` method, which accepts a query created through the N1qlQuery class.
You receive an array of objects representing the results through your specified callback.

The following example shows how to send a N1QL query:

[source,javascript]
----
var N1qlQuery = require('couchbase').N1qlQuery;
var myBucket = myCluster.openBucket();
var query = N1qlQuery.fromString('SELECT * FROM default');
myBucket.query(query, function(err, res) {
  if (err) {
    console.log(‘query failed’, err);
    return;
  }
  console.log(‘success!’, res);
});
----

Sample output from the example:

[source,javascript]
----
success! [
  { field_name: ‘value’ },
  { field_name: ‘value’ }
]
----

NOTE: Unlike `ViewQuery` type queries, the `N1qlQuery` type queries are not currently capable of streaming rows individually, and instead you must always receive the full result once the query has fully completed.

== Adhoc Queries vs Frequent Queries

When you often execute a `N1qlQuery` it can be interesting to let the SDK and the query engine attempt additional optimizations.

By default, a `N1qlQuery` will be considered "ad hoc" (no additional optimization is done).
By calling `.adhoc(false)` on your query you can mark it for further optimization by the SDK and the query engine.
It will be prepared on the server and all subsequent invocations of this query will benefit from the prepared execution plan.

TIP: Other `N1qlQuery` instances with the *same statement* (but different placeholder values for example) will also benefit from the optimization, as long as they are marked as `adhoc(false)`.

The SDK will retry to prepare a plan once if the server is unable to execute the cached plan.
It will cache plans for up to 5000 statements locally.
