= Performance tuning
:page-topic-type: concept

[abstract]
Follow the guidelines for effective use of resources.

Though the Node.js SDK and Couchbase Server are extremely performant, follow these guidelines to ensure the most effective use of your computing resources:

[#ol_abl_mwq_t4]
* Couchbase bucket connections are relatively expensive to establish in relation to the operations performed on them.
Because of this, you should open each bucket only once per application instance.
Due to multiplexing performed within the SDK, opening multiple connections can cause issues and will not benefit performance in most cases.
* Don't use too many views and buckets.
A large number of buckets or views can negatively affect the performance of Couchbase Server and any connected clients.
* Performing multiple operations simultaneously increases throughput and is important to achieving the best possible operation speeds.
This is possible by dispatching two discreet operations simultaneously rather than waiting for an operation callback.
You can also do this by using the *Multi versions of operations to perform multiple operations through a single function call.
