= Couchbase Node.js Release Notes and Download Archives


include::start-using-sdk.adoc[tag=prep]

include::start-using-sdk.adoc[tag=install]

To install an older version, specify the version directly with npm. 
For example, to install version 2.4.5:

[source,bash]
----
npm install couchbase@2.4.5
----


== Version 2.6.3 (February 8 2018)

Version 2.6.3 is a minor maintenance release of the 2.6 series.

[source,bash]
----
$ npm install couchbase@2.6.3
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.6.3/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-533[JSCBC-533]:
Added support for async contexts.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-526[JSCBC-526]:
Setting configuration changes on a bucket before connecting to it will no longer fail.
* http://issues.couchbase.com/browse/JSCBC-528[JSCBC-528]:
Fixed missing inline AnalyticsQuery documentation for bucket querying.
* http://issues.couchbase.com/browse/JSCBC-527[JSCBC-527]:
Improved error message for unknown HTTP errors.
* http://issues.couchbase.com/browse/JSCBC-541[JSCBC-541]:
Updated to libcouchbase 2.10.2.
* http://issues.couchbase.com/browse/JSCBC-542[JSCBC-542]:
Parameter handling rewritten for updated LCB operations in support of Analytics Ingress and Deferred Querying.
* http://issues.couchbase.com/browse/JSCBC-415[JSCBC-415]:
Improved tests to support variable cluster versions.
* http://issues.couchbase.com/browse/JSCBC-539[JSCBC-539]:
Traces now end at correct point for FTS and N1QL, covering entire operation.
* http://issues.couchbase.com/browse/JSCBC-540[JSCBC-540]:
Fixed Winston logging warning for newest loggers.
* http://issues.couchbase.com/browse/JSCBC-529[JSCBC-529]:
Added insert/upsert documentation in mutateIn method.


== Version 2.6.2 (4 December 2018)

Version 2.6.2 is a minor maintenance release of the 2.6 series.

[source,bash]
----
$ npm install couchbase@2.6.2
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.6.2/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-520[JSCBC-520]:
Added name property to Bucket objects for easier access.

== Version 2.6.1 (13 November 2018)

Version 2.6.1 is the first maintenance release of the 2.6 series.

[source,bash]
----
$ npm install couchbase@2.6.1
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.6.1/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-515[JSCBC-515]:
Fixed issue with special characters causing errors with Node 11.x.
* http://issues.couchbase.com/browse/JSCBC-517[JSCBC-517]:
Updated all third-party dependencies to their latest versions.
* Various minor changes.

== Version 2.6.0 (2 October 2018)

Version 2.6.0 is the first general availability release of the 2.6 series. 
It adds support for the upcoming Couchbase Server 6.0's features such as the new Analytics Service, improvements to Full Text Search, support for more complex network configurations along with many small improvements and fixes.

[source,bash]
----
$ npm install couchbase@2.6.0
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.6.0/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-497[JSCBC-497]:
Added expanded support for Couchbase Analytics, including parameterized
queries, support for rebalancing your analytics nodes and improved
customization of your analytics query performance.
* http://issues.couchbase.com/browse/JSCBC-508[JSCBC-508]:
Added ability to specify custom N1QL query options via a new
http://docs.couchbase.com/sdk-api/couchbase-node-client-2.6.0/N1qlStringQuery.html#rawParam[rawParam]
option.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-506[JSCBC-506]:
Fixed gets showing as stores in traces.
* http://issues.couchbase.com/browse/JSCBC-505[JSCBC-505]:
Fixed issue where Node.js event loop could get stuck running.
* http://issues.couchbase.com/browse/JSCBC-502[JSCBC-502]:
Fixed touch operations doing getAndTouch instead.
* http://issues.couchbase.com/browse/JSCBC-510[JSCBC-510]:
Fixed dropPrimaryIndex throwing exceptions.
* http://issues.couchbase.com/browse/JSCBC-509[JSCBC-509]:
Exposed some internal builders for promisification.
* http://issues.couchbase.com/browse/JSCBC-500[JSCBC-500]:
Added additional documentation to Bucket.mutateIn method.
* http://issues.couchbase.com/browse/JSCBC-499[JSCBC-499]:
Clarified options for Bucket.lookupIn method.
* http://issues.couchbase.com/browse/JSCBC-507[JSCBC-507]:
Updated to latest libcouchbase (2.9.5).

== Version 2.5.1 (27 July 2018)

Version 2.5.1 is the first maintenance release of the 2.5 series.

[source,bash]
----
$ npm install couchbase@2.5.1
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.5.1/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-457[JSCBC-457]:
Implemented new FTS Index Management API.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-486[JSCBC-486]: Corrected
memory leak of libcouchbase trace spans.
* http://issues.couchbase.com/browse/JSCBC-487[JSCBC-487]: Update to
latest libcouchbase version (2.9.3).
* Various minor bug fixes.

== Version 2.5.0 (5 July 2018)

Version 2.5.0 is the first general availability release of the
2.5 series. It adds support for the upcoming Couchbase Server 5.5.

[source,bash]
----
$ npm install couchbase@2.5.0
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.5.0/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-477[JSCBC-477]: Added
handling of incorrect certificate authentications configurations.
* http://issues.couchbase.com/browse/JSCBC-476[JSCBC-476]: Added
handling of incorrect mixed authentications configurations.
* http://issues.couchbase.com/browse/JSCBC-123[JSCBC-123]: Added
logging integration with libcouchbase.
* http://issues.couchbase.com/browse/JSCBC-472[JSCBC-472]: Added
additional libcouchbase build restrictions.
* Updated to latest dependencies.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-482[JSCBC-482]: Updated
to latest libcouchbase version (2.9.2).
* http://issues.couchbase.com/browse/JSCBC-481[JSCBC-481]: Fixed
missing methods for FTS querying.
* http://issues.couchbase.com/browse/JSCBC-471[JSCBC-471]: Fixed
issue with double destruction of internal io instances.
* Corrected minor inline documentation errors.

=== Known Issues

* A memory leak was found within this release related to the creation
of tracing spans. Users are encouraged to update to the 2.5.1
release of the SDK or to disable tracing temporarily until the
upgrade is completed by specifying `enable_tracing=false` in
their connection string.

== Version 2.4.5 (7 March 2018)

Version 2.4.5 is a maintenance release for the 2.4.x series.

[source,bash]
----
$ npm install couchbase@2.4.5
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.4.5/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-445[JSCBC-445]: Added
support for network compression.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-450[JSCBC-450]: Fix
incorrect query parameters for FTS numeric range facets.
* http://issues.couchbase.com/browse/JSCBC-452[JSCBC-452]: Fix
possible crash when closing buckets.
* http://issues.couchbase.com/browse/JSCBC-455[JSCBC-455]: Updated
all dependencies. 
* http://issues.couchbase.com/browse/JSCBC-454[JSCBC-454]: Upgraded
to libcouchbase 2.8.5

== Version 2.4.4 (7 February 2018)

Version 2.4.4 is a maintenance release for the 2.4.x series.

[source,bash]
----
$ npm install couchbase@2.4.4
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.4.4/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-408[JSCBC-408]: Added
method for pinging the server.
* http://390[JSCBC-390]: Added method for getting diagnostic info
from the client.
* http://issues.couchbase.com/browse/JSCBC-438[JSCBC-438]: Added
support for certificate-based authentication.
* http://issues.couchbase.com/browse/JSCBC-447[JSCBC-447]: Updated
all dependancies
* http://issues.couchbase.com/browse/JSCBC-446[JSCBC-446]: Updated
to libcouchbase 2.8.4

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-435[JSCBC-435]: Added
missing multi-value sub-document operations.

== Version 2.4.3 (5 December 2017)

Version 2.4.3 is a maintenance release for the 2.4.x series.

[source,bash]
----
$ npm install couchbase@2.4.3
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.4.3/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-430[JSCBC-430]: Added
initial support for IPv6.
* http://issues.couchbase.com/browse/JSCBC-439[JSCBC-439]: Added
ability to fetch couchbase library from a bucket.
* http://issues.couchbase.com/browse/JSCBC-434[JSCBC-434]: Updated
all dependancies to latest releases.
* http://issues.couchbase.com/browse/JSCBC-436[JSCBC-436]: Update to
latest libcouchbase (2.8.3).

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-440[JSCBC-440]: Fixed
issue where tests did not end gracefully.
* http://issues.couchbase.com/browse/JSCBC-433[JSCBC-433]: Fixed
issue with incorrect DocIdQuery creation.
* http://issues.couchbase.com/browse/JSCBC-432[JSCBC-432]: Fixed
issue with missing BooleanFieldQuery methods.
* Various minor fixes.

== Version 2.4.2 (7 November 2017)

Version 2.4.2 is a maintenance release for the 2.4.x series.

[source,bash]
----
$ npm install couchbase@2.4.2
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.4.2/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-423[JSCBC-423]: Added
support for Analytics authentication.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-428[JSCBC-428]: Improved
error handling for network errors during HTTP requests.
* http://issues.couchbase.com/browse/JSCBC-424[JSCBC-424]: Fix a
crash in N1QL introduced in 2.4.0.
* http://issues.couchbase.com/browse/JSCBC-422[JSCBC-422]: Added
missing methods to Search querying.
* Various minor fixes.

== Version 2.4.1 (3 October 2017)

Version 2.4.1 is a maintenance release for the 2.4.x series.

[source,bash]
----
$ npm install couchbase@2.4.1
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.4.1/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-440[JSCBC-420]: Fixed
issue causing getReplica to fail in some instances.
* http://issues.couchbase.com/browse/JSCBC-377[JSCBC-377]: Correctly
handle N1QL errors during result set streaming.

== Version 2.4.0 (7 September 2017)

Version 2.4.0 is the first general availability release of the
2.4 series. It adds new features for Couchbase Server 5.0.

[source,bash]
----
$ npm install couchbase@2.4.0
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-2.4.0/[API Reference]

=== Fixed Issues

* https://issues.couchbase.com/browse/JSCBC-418[JSCBC-418:] Enabled
Server 5.0 error mapping.
* https://issues.couchbase.com/browse/JSCBC-419[JSCBC-419:] Updated
to latest libcouchbase (2.8.0).
* https://issues.couchbase.com/browse/JSCBC-404[JSCBC-404]: Added
additional Server 5.0 N1QL options.

== Version 2.3.7 (22 August 2017)

Version 2.3.7 is a maintenance release for the 2.x series.

[source,bash]
----
$ npm install couchbase@2.3.7
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-2.3.7/[API Reference]

=== Fixed Issues {#fixed-issues-8 style="text-align:left"}

* http://issues.couchbase.com/browse/JSCBC-406[JSCBC-406]: Enable
SSL on built-in libcouchbase build.
* http://issues.couchbase.com/browse/JSCBC-411[JSCBC-411]:
Implemented usage of CouchbaseMock for integrated testing.
* Various minor bug fixes

== Version 2.3.6 (3 August 2017)

Version 2.3.6 is a maintenance release for the 2.x series.

[source,bash]
----
$ npm install couchbase@2.3.6
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-2.3.6/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-397[JSCBC-397]: Send view
query keys via POST rather than GET.
* http://issues.couchbase.com/browse/JSCBC-400[JSCBC-400]: Don't
include empty data in management errors.
* http://issues.couchbase.com/browse/JSCBC-393[JSCBC-393]:
Implemented domain option on user management APIs.
* http://issues.couchbase.com/browse/JSCBC-398[JSCBC-398]: Updated
to latest libcouchbase (2.7.6).
* Various minor bug fixes

== Version 2.3.5 (12 July 2017)

Version 2.3.5 is a minor release for the 2.x series.

[source,bash]
----
$ npm install couchbase@2.3.5
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-2.3.5/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-395[JSCBC-395]:
Fixed issue causing buildDeferredIndexes to error.
* http://issues.couchbase.com/browse/JSCBC-396[JSCBC-396]:
Fixed issue where getIndexes returned unexpected indexes.
* http://issues.couchbase.com/browse/JSCBC-384[JSCBC-384]:
Implemented experimental 5.0.0 user management API.
* http://issues.couchbase.com/browse/JSCBC-386[JSCBC-386]:
Fixed issue with subdoc legacy createParents.
* Various minor bug fixes

== Version 2.3.4 (7 June 2017)

Version 2.3.4 is a minor release for the 2.x series.

[source,bash]
----
$ npm install couchbase@2.3.4
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-2.3.4/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-342[JSCBC-342]: Added
experimental support for extended attributes.
* http://issues.couchbase.com/browse/JSCBC-365[JSCBC-365]: Added
support for new FTS geo and sorting features.
* http://issues.couchbase.com/browse/JSCBC-381[JSCBC-381]: Fixed
subdocument exists returning incorrect results.
* http://issues.couchbase.com/browse/JSCBC-382[JSCBC-382]: Update to
libcouchbase v2.7.5.
* Updated to latest prebuild installation flow.
* Various minor bug fixes

== Version 2.3.3 (2 May 2017)

Version 2.3.3 is a minor release for the 2.x series.

[source,bash]
----
$ npm install couchbase@2.3.3
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-2.3.3/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-356[JSCBC-356]:
Implemented an role-based authenticator.
* http://issues.couchbase.com/browse/JSCBC-368[JSCBC-368]: Updated
RBAC user management with new API endpoints.
* http://issues.couchbase.com/browse/JSCBC-372[JSCBC-372]:
Implemented method to allow flushing of the query cache.
* http://issues.couchbase.com/browse/JSCBC-375[JSCBC-375]: Exposed
all libcouchbase error codes to Node.js.
* http://issues.couchbase.com/browse/JSCBC-371[JSCBC-371]:
Update to libcouchbase v2.7.4.
* Various minor bug fixes

== Version 2.3.2 (4 April 2017)

Version 2.3.2 is a minor release for the 2.x series.

[source,bash]
----
$ npm install couchbase@2.3.2
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-2.3.2/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-361[JSCBC-361]:
Implement experimental role-based user management.
* http://issues.couchbase.com/browse/JSCBC-363[JSCBC-363]:
Update to libcouchbase v2.7.3.
* Various minor bug fixes

== Version 2.3.1 (7 March 2017)

Version 2.3.1 is a minor release for the 2.x series.

[source,bash]
----
$ npm install couchbase@2.3.1
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-2.3.1/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-353[JSCBC-353]: Do not
corrupt BooleanQuery should value.
* http://issues.couchbase.com/browse/JSCBC-352[JSCBC-352]: Update to
latest dependencies and fix build warnings.
* http://issues.couchbase.com/browse/JSCBC-358[JSCBC-358]: Update to
libcouchbase v2.7.2.
* Various minor bug fixes

== Version 2.3.0 (4 January 2017)

Version 2.3.0 is a server-aligned release for the 2.x series.

[source,bash]
----
$ npm install couchbase@2.3.0
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-2.3.0/[API Reference]

=== Fixed Issues

* All server 4.6 feature APIs have been moved from uncommitted to
committed.
* http://issues.couchbase.com/browse/JSCBC-343[JSCBC-343]: Updated
to libcouchbase 2.7.0.
* http://issues.couchbase.com/browse/JSCBC-341[JSCBC-341]: Implement
latest changes to FTS RFC.
* Added support for FTS `pretty` option.

== Version 2.2.5 (7 December 2016)

Version 2.2.5 is a bug-fix release for the 2.2 serries.

[source,bash]
----
$ npm install couchbase@2.2.5
----

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-340[JSCBC-340]:
Added queue data-structure support.
* http://issues.couchbase.com/browse/JSCBC-328[JSCBC-328]: Fix bug
with cluster management error handling.
* Fixed bug which could cause an infinite recursion.
* Renamed some data-structures related methods.

== Version 2.2.4 (1 November 2016)

Version 2.2.4 is a bug-fix release for the 2.2 series.

[source,bash]
----
$ npm install couchbase@2.2.4
----

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-339[JSCBC-339]: Added
experimental support for CBAS.

== Version 2.2.3 (4 October 2016)

Version 2.2.3 is a bug-fix release of the 2.2 series.

[source,bash]
----
$ npm install couchbase@2.2.3
----

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-326[JSCBC-326]: Added
ability to specify batch size for getMulti.
* http://issues.couchbase.com/browse/JSCBC-273[JSCBC-273]: Implement
data-structures as per current RFC.
* http://issues.couchbase.com/browse/JSCBC-329[JSCBC-329]: Do not
invoke callbacks within callback try-catch blocks.
* http://issues.couchbase.com/browse/JSCBC-334[JSCBC-334]: Fix
incorrect bucket name references in index management API.
* http://issues.couchbase.com/browse/JSCBC-331[JSCBC-331]: Updated
to latest cluster-level-auth RFC.
* http://issues.couchbase.com/browse/JSCBC-336[JSCBC-336]: Updated
to libcouchbase 2.6.3
* Various minor bug fixes

== Version 2.2.2 (2 August 2016)

Version 2.2.2 is a bug-fix release of the 2.2 series.

[source,bash]
----
$ npm install couchbase@2.2.2
----

=== Fixed Issues

* https://issues.couchbase.com/browse/JSCBC-313[JSCBC-313]: Improved
documentation of Couchbase Search API.
* https://issues.couchbase.com/browse/JSCBC-322[JSCBC-322]: Fixed
minor API bugs in Couchbase Search API.
* https://issues.couchbase.com/browse/JSCBC-306[JSCBC-306]: Improve
error handling of management operations.
* https://issues.couchbase.com/browse/JSCBC-316[JSCBC-316]: Fix
crash in certain MDS cluster configurations.
* https://issues.couchbase.com/browse/JSCBC-321[JSCBC-321]: Updated
to libcouchbase v2.6.2.
* Various minor bug fixes

== Version 2.2.1 (23 June 2016)

Version 2.2.1 is a minor bug-fix release of the 2.2 series.

[source,bash]
----
$ npm install couchbase@2.2.1
----

=== Fixed Issues

* Corrected incorrect sub-document API method names.

== Version 2.2.0 (21 June 2016)

Version 2.2.0 is the first general availability release of the 2.2
series. It adds new features for N1QL query, performance enhancements
and supports the developer preview full text search available in
Couchbase Server 4.5. A number of these features were added as
uncommitted API in the 2.1 series and are now promoted to committed API.

 $ npm install couchbase@2.2.0

=== New Features and Behavioral Changes

* https://issues.couchbase.com/browse/JSCBC-281[JSCBC-281]: Support
for Index Management.
* https://issues.couchbase.com/browse/JSCBC-274[JSCBC-274]: Support
for Sub-Document API.
* https://issues.couchbase.com/browse/JSCBC-381[JSCBC-381]: Support
for Couchbase Server Full Text Search (FTS) Developer Preview.

=== Fixed Issues

* https://issues.couchbase.com/browse/JSCBC-306[JSCBC-306]: Bucket
management operations do not indicate status code errors.
* https://issues.couchbase.com/browse/JSCBC-305[JSCBC-305]: Query
options consistency and ConsistentWith do not behave as expected
with regard to their exclusivity.
