= MapReduce Views Using the Node.js SDK with Couchbase Server
:navtitle: MapReduce Views
:page-aliases: managing-views,querying-views,howtos:view-queries-with-sdk,concept-docs:understanding-views

[abstract]
You can use MapReduce views to create queryable secondary indexes in Couchbase Server.

include::6.0@sdk:shared:partial$views.adoc[tag=views-intro]

include::6.0@sdk:shared:partial$views.adoc[tag=example-beer]

include::6.0@sdk:shared:partial$views.adoc[tag=example-geo-travel]

== Querying Views through the Node.js SDK

Querying a view through the Node.js client is performed through the `ViewQuery` class that is available as a top-level object.

[source,javascript]
----
var couchbase = require('couchbase');
var ViewQuery = couchbase.ViewQuery;

var query = ViewQuery.from('beer', 'by_name');
----

A `ViewQuery` object enables you to query the view and specify various available options for the query.
Once you have the query ready for execution, pass it to the `query` method of the your Bucket instance:

[source,javascript]
----
var myBucket = myCluster.openBucket();
myBucket.query(query, function(err, results) {
  for(i in results)
    console.log(results[i]);
});
----

You can modify your view results by specifying various options before executing the `query` method.
Here is an example that skips the first six items and limits the results to three items:

[source,javascript]
----
var query = ViewQuery.from('beer', 'by_name').skip(6).limit(3);
myBucket.query(query, function(err, results) {
  for(i in results)
    console.log(results[i]);
});
----

If you are interested in performing a geospatial view, simply use `SpatialQuery` as your root rather than `ViewQuery`.

[source,javascript]
----
var SpatialQuery = couchbase.SpatialQuery;

var query = SpatialQuery.from('spatial', 'by_location').limit(10);
myBucket.query(query, function(err, results) {
  for(i in results)
    console.log(results[i]);
});
----
