= Logging
:description: Node.js SDK logging.
:page-topic-type: howto

[abstract]
{description}


IMPORTANT: the Logging implementation has changed substantially in 4.x.
Customized logging is not yet implemented, this will be resolved in a future 4.x release.
Use of the console logger (detailed below) is currently recommended.

== Library logging

The Node.js SDK allows logging via the `CBPPLOGLEVEL` environment variable.
// TODO: This section seems outdated? Unclear what we should keep and what needs to be discarded for SDK 4.x.
// The Node.js SDK offers a basic logging facility through which its various subsystems can output
// debug and error information.
// This information provides details of the library's internals and additional error information
// which may otherwise not be accessible via other APIs.
// Logging may be enabled via the `debug` library, an environment variable, or a connection string directive.

// The most common way to enable logging is to set the `DEBUG` environment variable to `couchnode*`.
// Alternatively you can set the `LCB_LOGLEVEL` environment variable to a number between 1 and 5,
// with 5 being the most verbose and 1 being the least verbose.  Also, the query parameter
// `console_log_level` can be used to set the log level.
Note that these logs will go to `stderr` --
on most developers' laptops, `stderr` will be redirected to `stdout` (standard output), and displayed in the terminal running the app.
Redirection to a log file may depend upon which shell you use.
For the `BASH` shell, for example, see the https://tldp.org/LDP/abs/html/io-redirection.html[Bash Scripting Guide^].

=== Environmental Settings

In the command line environment, the `CBPPLOGLEVEL` variable is set as follows:

.GNU/Linux and Mac
[source,console]
----
export CBPPLOGLEVEL=<log-level>
----

.Windows
[source,console]
----
set CBPPLOGLEVEL=<log-level>
----

Version 4.4.3 of the SDK introduces the `CBPPLOGFILE` variable that can be used in conjunction with `CBPPLOGLEVEL`.
Set `CBPPLOGFILE` to a filename in order to have the log output to a file (instead of `stderr`).

In the command line environment, the `CBPPLOGFILE` variable is set as follows:

.GNU/Linux and Mac
[source,console]
----
export CBPPLOGFILE=<filename>
----

.Windows
[source,console]
----
set CBPPLOGFILE=<filename>
----

== Log Levels

You can increase the log level for greater verbosity (more information) in the logs:

* off -- disables all logging, which is normally set by default.
* error -- error messages.
* warn -- error notifications.
* info -- useful notices, not often.
* debug -- diagnostic information, minimum level required to investigate problems.
* trace -- detailed diagnostic information, often required to investigate problems.

When logging is turned on, the SDK will output messages similar to this:

[source,console]
----
[2022-05-17 15:23:46.221] [85833,13741777] [debug] 1ms, [2aed64fd-5d38-416a-cc09-e67c371b8444]: use default CA for TLS verify
----




////
== Log Redaction

Redacting logs is a two-stage process.
If you want to redact client logs (for example before handing them off to the Couchbase Support team) you first need to enable log redaction in your application.
This is done through the https://docs.couchbase.com/sdk-api/couchbase-python-client/couchbase_api/options.html#clusteroptions[`ClusterOptions`], setting `log_redaction` to `True`.

Once the SDK writes the logs with the tags to a file, you can then use the
xref:{version-server}@server:cli:cbcli/cblogredaction.adoc[`cblogredaction` tool] to obfuscate the log.

* You may wish to read more on Log Redaction
xref:{version-server}@server:manage:manage-logging/manage-logging.adoc#understanding_redaction[in the Server docs].
////



== SDK Telemetry from the Server

In addition to Tracing and other metrics, and client logging, SDK telemetry is also sent to the Server -- available from 8.0, and in new Capella Operational clusters -- for ingestion with other Prometheus metrics.
Capella Operational exposes these metrics through the UI.

For self-managed Server, collection can be disabled and enabled through the REST API:

[source,console]
----
curl --user Administrator:password http://172.17.0.2:8091/settings/appTelemetry -d enabled=true
----

And the Prometheus-format metrics fetched with:

[source,console]
----
curl --user Administrator:password http://172.17.0.2:8091/metrics
----

Further details can be found in the xref:{version-server}@server:rest-api:application-telemetry.adoc[] page.

There may be advantages to collecting information this way,
but note that metrics are collected per node,
and a central Prometheus instance should be set to collect all metrics so that information is not lost in case of a sudden failover.

Also note that if the cluster is behind a load balancer, the collected metrics may not accurately record the actual correct node with which the SDK interacts.













// TODO: Is this still valid? Unclear what 'options' we are referring to...
// NOTE: The output format is subject to change.
// It is intended for human consumption and is not designed to be parseable.
// Different formats can be specified by providing a custom logging function in the 'options' argument.

// The following table describes the components of the log entries:

// [cols="50,213"]
// |===
// | Format | Description

// | `nms`
// | The number of milliseconds elapsed since the loading of the library

// | `[In]`
// | The identifier of the `lcb_t` object associated with the current message.
// This allows you to determine the origin of the message in the case where the application contains multiple such `lcb_t` objects.
// The number is incremented for each call to [.api]`lcb_create()`

// | `+{PID}+`
// | The current thread/process identifier.
// On Linux this is also the process ID for single-threaded programs, further helping distinguish between multiple forks of an application.

// | `[LEVEL]`
// | A string representing the severity of the level

// | `(subsystem - L:line)`
// | The _subsystem_ that produced this message, followed by the source code line at which this message was created.
// The subsystem will typically, but not always, resemble the source code file.
// It is a small string describing what the current line is doing.

// | `<host:port>`
// | The host and port, if any, associated with the message.
// This is supplied for messages that relate to the state of a particular connection.
// |===

////
== Additional Information

The Node.js SDK internally uses the libcouchbase API (since 4.0 implemented by the Couchbase++ library) to perform operations.
If more in depth debug information is required such as Stack Traces or Memory Leak Detection, you can find more information on how to achieve this in xref:c-sdk:howtos:collecting-information-and-logging.adoc[the C SDK documentation].
////
