= Concurrent Document Mutations
:page-topic-type: howto
include::partial$attributes.adoc[]

[abstract]
You can use the CAS value to control how concurrent document modifications are handled.
It helps avoid and control potential race conditions in which some mutations may be inadvertently lost or overridden by other mutations.


The _CAS_ -- _Compare and Swap_ -- is a value representing the current state of an item.
Each time the item is modified, its CAS changes.

The CAS value itself is returned as part of a document’s metadata whenever a document is accessed.
In the SDK this is present as the `cas` field in the applicable document container object when an operation is successful.
// needs improving ^


// something something optimistic locking.
The CAS can be supplied as parameters to the _insert_, _upsert_, _replace_, and _remove_ operations.
When applications provide the CAS, server will check the application-provided version of CAS against its own version of the CAS:

* If the two CAS values match (they compare successfully), then the mutation operation succeeds.
* If the two CAS values differ, then the mutation operation fails.
