= Concurrent Document Mutations
:page-topic-type: howto
include::partial$attributes.adoc[]

include::6.5@sdk:shared:partial$cas.adoc[tag=intro]

include::6.5@sdk:shared:partial$cas.adoc[tag=demo]

include::6.5@sdk:shared:partial$cas.adoc[tag=example]

[source,javascript]
----
async function incrementVisitCount(collection, userId) {
    var maxRetries = 10;
    for(var i = 0; i < maxRetries; ++i) {
        // Get the current document contents
        var getRes = await collection.get(userId);

        // Increment the visit count
        var userDoc = getRes.value;
        userDoc.visitCount++;

        try {
            // Attempt to replace the document using CAS
            await collection.replace(userId, userDoc, {cas: getRes.cas});
        } catch (e) {
            // Check if the error thrown is a cas mismatch, if it is, we retry
            if (e instanceof couchbase.CasMismatchError) {
                continue;
            }
            throw e;
        }

        // If no errors occured during the replace, we can exit our retry loop
        break;
    }
}
----

Sometimes more logic is needed when performing updates, for example, if a property is mutually exclusive with another property; only one or the other can exist, but not both.


include::6.5@sdk:shared:partial$cas.adoc[tag=performance]

include::6.5@sdk:shared:partial$cas.adoc[tag=format]

include::6.5@sdk:shared:partial$cas.adoc[tag=locking]

[source,javascript]
----
var getRes = await collection.getAndLock('key');

var lockedCas = getRes.cas;

/** an example of simply unlocking the document:
await collection.unlock('key', lockedCas);
 */

await collection.upsert('key', 'new value', {cas: lockedCas});
----

The handler will unlock the item either via an explicit unlock operation ([.api]`unlock`) or implicitly via modifying the item with the correct CAS.

If the item has already been locked, the server will respond with CasMismatch which means that the operation could not be executed temporarily, but may succeed later on.



////


= Concurrent Document Mutations
:page-topic-type: howto
include::partial$attributes.adoc[]

[abstract]
You can use the CAS value to control how concurrent document modifications are handled.
It helps avoid and control potential race conditions in which some mutations may be inadvertently lost or overridden by other mutations.


The _CAS_ -- _Compare and Swap_ -- is a value representing the current state of an item.
Each time the item is modified, its CAS changes.

The CAS value itself is returned as part of a document’s metadata whenever a document is accessed.
In the SDK this is present as the `cas` field in the applicable document container object when an operation is successful.
// needs improving ^


// something something optimistic locking.
The CAS can be supplied as parameters to the _insert_, _upsert_, _replace_, and _remove_ operations.
When applications provide the CAS, server will check the application-provided version of CAS against its own version of the CAS:

* If the two CAS values match (they compare successfully), then the mutation operation succeeds.
* If the two CAS values differ, then the mutation operation fails.
////