= Full Text Search (FTS) Using the Node.js SDK with Couchbase Server
:navtitle: Searching from the SDK
:page-topic-type: howto

[abstract]
You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.

Full Text Search (FTS) allows you to create, manage, and query full-text indexes on JSON documents stored in Couchbase buckets.

Using natural language processing for querying documents, FTS provides relevance scoring on the results AKA 'hits' from your queries, and has fast indexes for querying a wide range of possible text searches.

Supported query types include simple queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.

The Couchbase Node.js SDK exposes an API for performing FTS queries which abstract some of the complexity of using the underlying REST API.

// As of Couchbase Server 6.5, FTS...

== Examples

Search queries are executed at the cluster level (not bucket or collection). All of the examples below will log to the console our returned documents along with their metadata and rows, each returned document has an index, id, score and sort value.

Below is a simple FTS SearchQuery that uses the `match()` method to find a specified term: “five-star”.

[source,javascript]
----
async function ftsMatchWord(term) {
  try {
    return await cluster.searchQuery(
      'index-hotel-description', 
      couchbase.SearchQuery.match(term),
      { limit: 5 }
    );
  } catch (error) {
    console.error(error)
  }
}

ftsMatchWord('five-star')
  .then((result) => console.log(result))
----

Below is a simple FTS SearchQuery that uses the `matchPhrase()` method to find a specified phrase: “Yosemite Valley”.

[source,javascript]
----
async function ftsMatchPhrase(phrase) {
  try {
    return await cluster.searchQuery(
      'index-hotel-description', 
      couchbase.SearchQuery.matchPhrase(phrase),
      { limit: 5 }
    );
  } catch (error) {
    console.error(error)
  }
}

ftsMatchPhrase('Yosemite Valley')
  .then((result) => console.log(result))
----

Below is a simple FTS SearchQuery that uses the `dateRange()` method to find a brewery from our `beer-sample` dataset where the updated field which is a date falls within a specified specified date range.

[source,javascript]
----
async function ftsBreweryUpdatedByDateRange(startDate, endDate) {
  try {
    return await cluster.searchQuery(
      'index-brewery-by-daterange', 
      couchbase.SearchQuery.dateRange()
        .start(startDate)
        .end(endDate),
      { limit: 5 }
    );
  } catch (error) {
    console.error(error)
  }
}

ftsBreweryUpdatedByDateRange('2010-11-10', '2010-11-20')
  .then((result) => console.log(result))
----

A conjunction query contains multiple child queries; its resulting documents or 'hits' must satisfy all child queries. The example below will only return one document because its description has the word 'Five star' and 'luxury hotel' while no other documents match both criteria.


[source,javascript]
----
async function ftsConjunction() {
  try {
    return await cluster.searchQuery(
      'index-hotel-description',
      couchbase.SearchQuery.conjuncts(
        couchbase.SearchQuery.match('five-star'),
        couchbase.SearchQuery.matchPhrase('luxury hotel')
      )
    );
  } catch (error) {
    console.error(error)
  }
}

ftsConjunction()
  .then((result) => console.log(result.rows))
----

Note: Our match for 'five-star' was not exact, but still produced a result because a similar term was found 'Five star', we could have potentially matched '5 star' or the word 'five'. When you work with any full-text search the number of hits you get and their score are variable.

== Working with Results

As with all query result types in the Node.js SDK, the search query results object contains two properties. The hits reflecting the documents that matched your query, emitted as rows. Along with the metadata available in the meta property.  

Metadata holds additional information not directly related to your query, such as success total hits and how long the query took to execute in the cluster.

[source,javascript]
.Iterating over hits
----
ftsConjunction().then(
  result => {
    result.rows.forEach((hit, index) => {
      console.log(`
        Result #${index+1} 
        ID: ${hit.id} 
        Score: ${hit.score}`)
    })
  }
)
----

//[source,csharp]
//.Iterating facets
//----
//result.meta.facets.forEach((facet) => {
//    var name = facet.name;
//    var total = facet.total;
//    // ...
//});
//----

== Consistency

Like the majority of Couchbase query services, FTS allows `RequestPlus` queries --
_Read-Your-Own_Writes (RYOW)_ consistency, ensuring results contain information from
updated indexes:

[source,javascript]
----
return cluster.searchQuery(
  'index-hotel-description',
  couchbase.SearchQuery.match('five-star'),
  { consistency: couchbase.Consistency.RequestPlus }
);
----
