= Key Value Operations
:navtitle: KV Operations
:page-topic-type: howto
:page-aliases: document-operations.adoc


////
The complete code sample used on this page can be downloaded from
  xref::example$document.cs[here]
- from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Bucket operations.
////

== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the Node.js SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation at its simplest:

.Insert
[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=insert,indent=0]
----

Options may be added to operations:

.Insert (with options)
[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=insertwithoptions,indent=0]
----

Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.

_timeout_ is an optional parameter which is represented in milliseconds.
Timeout sets the timeout value for the operation. We will add to these options
for the _Replace_ example:

[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=replace,indent=0]
----

Expiration sets an explicit time to live (TTL) for a document.
We'll discuss modifying `Expiration` in more details xref:#expiration-ttl[below].
For a discussion of item (Document) _vs_ Bucket expiration, see the 
xref:6.5@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].


== Durability

[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=durability,indent=0]
----

Here, we have added _Durability_ options, namely `persistTo` and `replicateTo`.
In Couchbase Server releases before 6.5, Durability was set with these two options 
-- see the xref:2.6@nodejs-sdk::durability.adoc[6.0 Durability documentation] 
-- covering  how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist. 
If a version of Couchbase Server lower than 6.5 is being used then the application can fall-back to this xref:concept-docs:durability-replication-failure-considerations.adoc#older-server-versions['client verified' durability]. 

If 6.5 or above is being used, you can take advantage of the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[Durable Write] feature, 
in which Couchbase Server will only return success to the SDK after the requested replication level has been achieved. 
The three replication levels are:

 * `Majority` - The server will ensure that the change is available in memory on the majority of configured replicas.
 * `MajorityAndPersistToActive` - Majority level, plus persisted to disk on the active node.
 * `PersistToMajority` - Majority level, plus persisted to disk on the majority of configured replicas.

The options are in increasing levels of safety. 
Note that nothing comes for free - for a given node, waiting for writes to storage is considerably slower than waiting for it to be available in-memory.
These trade offs, as well as which settings may be tuned, are discussed in the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[durability page].

The following example demonstrates using the newer durability features available in Couchbase server 6.5 onwards.

[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=newdurability,indent=0]
----

To stress, durability is a useful feature but should not be the default for most applications, as there is a performance consideration, 
and the default level of safety provided by Couchbase will be reasonable for the majority of situations.

[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Document Operations].
====

== Retrieving full documents

Using the `get()` method with the document key can be done in a similar fashion to the other operations:

[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=get,indent=0]
----

Timeout can also be set - as in the earlier `Insert` example:

.Get (with options)
[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=getwithoptions,indent=0]
----


== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

.Remove (with options)
[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=remove,indent=0]
----

== Expiration / TTL

By default, Couchbase documents do not expire, but transient or temporary data may be needed for user sessions, caches, or other temporary documents. 
Using `touch()`, you can set expiration values on documents to handle transient data:

[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=touch,indent=0]
----

A network timeout can be set with the options, in the same fashion as earlier examples on this page:

[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=touchwithoptions,indent=0]
----

include::6.5@sdk:shared:partial$documents.adoc[tag=exp-note]


== Atomic Counters

The value of a document can be increased or decreased atomically using `binary().increment()` and `binary().decrement()`.

.Increment
[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=increment,indent=0]
----

.Increment (with options)
[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=incrementwithoptions,indent=0]
----

.Decrement
[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=decrement,indent=0]
----

.Decrement (with options)
[source,javascript]
----
include::devguide:example$nodejs/kv-operations.js[tag=decrementwithoptions,indent=0]
----

NOTE: Increment & Decrement are considered part of the ‘binary’ API and as such may still be subject to change

== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.

Another way of increasing network performance is to _pipeline_ operations with xref:concurrent-async-apis.adoc#batching[Batching Operations].

As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:concept-docs:nonjson.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of N1QL.
