= Managing Connections
:description: This section describes how to connect the Node.js SDK to a Couchbase cluster.
:page-topic-type: howto
:page-aliases: ROOT:managing-connections,howtos:multi-network,ROOT:connecting,ROOT:connection-advanced

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
It contains best practices as well as information on TLS/SSL and other advanced connection options.

== Connecting to a Cluster

A connection to a Couchbase Server cluster is represented by a `Cluster` object.
A `Cluster` provides access to Buckets, Scopes, and Collections, as well as various Couchbase services and management interfaces.
The simplest way to create a `Cluster` object is to `const cluster = couchbase.connect` with a username, and password:

[source,javascript]
----
include::example$auth.js[tag=rbac-auth,indent=0]
----

NOTE: If you are connecting to a version of Couchbase Server older than 6.5, it will be more efficient if the addresses are those of data (KV) nodes.
You will in any case, with 6.0 and earlier, need to open a ``Bucket` instance before connecting to any other HTTP services (such as _Query_ or _Search_.

Connection String options are covered https://docs.couchbase.com/sdk-api/couchbase-node-client/interfaces/ConnectOptions.html[in the API guide].


In a production environment, your connection string should include the addresses of multiple server nodes in case some are currently unavailable.
Multiple addresses may be specified in a connection string by delimiting them with commas:

[source,javascript]
----
include::example$auth.js[tag=many-hosts,indent=0]
----

TIP: You don't need to include the address of every node in the cluster.
The client fetches the full address list from the first node it is able to contact.


[#connection-strings]
== Connection Strings

A Couchbase connection string is a comma-delimited list of IP addresses and/or hostnames, optionally followed by a list of parameters.

The parameter list is just like the query component of a URI; name-value pairs have an equals sign (`=`) separating the name and value, with an ampersand (`&`) between each pair.
Just as in a URI, the first parameter is prefixed by a question mark (`?`).

.Simple connection string with one seed node
----
couchbase://127.0.0.1
----

.Connection string with two seed nodes
----
couchbase://nodeA.example.com,nodeB.example.com
----

.Connection string with two parameters
----
couchbase://127.0.0.1?network=external&operation_timeout=10.0
----

The full list of recognized parameters is documented in the https://docs.couchbase.com/sdk-api/couchbase-node-client/interfaces/ConnectOptions.html[API reference].

A connection string may optionally be prefixed by either "couchbase://" or "couchbases://".
If you wish to use TLS, the connection string must be configured as described in <<ssl>>.

[#connection-lifecycle]
== Connection Lifecycle

We recommend creating a single `Cluster` instance when your application starts up, and sharing this instance throughout your application.
Each of the respective sub-instances (Bucket, Collection, etc...) of the Cluster class can be stored and re-used, or created in an on-demand fashion whenever needed.

Before your application stops, gracefully shut down the client by calling the `close()` method of each `Cluster` you created.


== Alternate Addresses and Custom Ports

If your Couchbase Server cluster is running in a containerized, port mapped, or otherwise NAT'd environment like Docker or Kubernetes,
a client running outside that environment may need additional information in order to connect to the cluster.
Both the client and server require special configuration in this case.

On the server side, each server node must be configured to advertize its external address as well as any custom port mapping.
This is done with the `setting-alternate-address` CLI command introduced in Couchbase Server 6.5.
A node configured in this way will advertise two addresses:
one for connecting from the same network, and another for connecting from an external network.

On the client side, the externally visible ports must be used when connecting.
If the external ports are not the default, you can specify custom ports by explicitly specifying them in the connection string:

[source,javascript]
----
include::example$auth.js[tag=alt-addresses,indent=0]
----

To verify how the connection string is being deconstructed by the library, our C SDK's [.cmd]`cbc connstr` may also be used:

====
[source,console]
----
$ cbc connstr 'couchbase://localhost:1234,localhost:2345=http?network=external&timeout=10.0'
----

[source,console]
----
Bucket:
Implicit port: 11210
SSL: DISABLED
Boostrap Protocols: CCCP,HTTP
Hosts:
  [memcached]         localhost:1234
  [restapi]           localhost:2345
Options:
  network=external
  timeout=10.0
----
====

In many cases the client is able to automatically select the correct set of addresses to use when connecting to a cluster that advertises multiple addresses.

If the detection heuristic fails in your environment, you can override it by setting the `network` client setting to `default` if the client and server are on the same network, or `external` if they're on different networks.

NOTE: Any TLS certificates must be set up at the point where the connections are being made.


[#ssl]
== Secure Connections

Couchbase Server Enterprise Edition and Couchbase Capella support full encryption of client-side traffic using Transport Layer Security (TLS).
This includes key-value type operations, queries, and configuration communication.
Make sure you have the Enterprise Edition of Couchbase Server, or a Couchbase Capella account, before proceeding with configuring encryption on the client side.

For TLS verification the SDK uses the following certificates:

* The certificates in the Mozilla Root CA bundle (bundled with the SDK as of 4.2.4 and obtained from https://curl.se/docs/caextract.html[curl]).
* The certificates in OpenSSL’s default certificate store (as of 4.2.0).
* The self-signed root certificate that is used to sign Capella Certificates (bundled with the SDK as of 4.1.0).

The OpenSSL defaults can be overridden using the `SSL_CERT_DIR` and `SSL_CERT_FILE` environment variables. 
The `SSL_CERT_DIR` variable is used to set a specific directory in which the client should look for individual certificate files, whereas the `SSL_CERT_FILE` environment variable is used to point to a single file containing one or more certificates. 
More information can be found in the relevant https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_load_verify_locations.html[OpenSSL documentation].

Loading the Mozilla certificates can be disabled using the `disable_mozilla_ca_certificates` connection string parameter.

The {cbpp} core’s metadata provide information about where OpenSSL’s default certificate store is located, which version of the Mozilla Root CA store is bundled with the SDK, and other useful details. 
You can obtain the metadata using the following command:

====
[source,console]
----
$ node -p "JSON.parse(require('couchbase').cbppMetadata)"
----

[source,console]
----
{
  ...
  mozilla_ca_bundle_date: 'Tue Jan 10 04:12:06 2023 GMT',
  mozilla_ca_bundle_embedded: true,
  mozilla_ca_bundle_sha256: 'fb1ecd641d0a02c01bc9036d513cb658bbda62a75e246bedbc01764560a639f0',
  mozilla_ca_bundle_size: 137,
  ...
  openssl_default_cert_dir: '/opt/homebrew/etc/openssl@1.1/certs',
  openssl_default_cert_dir_env: 'SSL_CERT_DIR',
  openssl_default_cert_file: '/opt/homebrew/etc/openssl@1.1/cert.pem',
  openssl_default_cert_file_env: 'SSL_CERT_FILE',
  ...
}
----
====
With debug-level logging enabled, if the Mozilla certificates have been loaded, a message with the information about the version of the Mozilla CA certificate store will be outputted. 
For example:

[source,console]
----
[2023-05-17 15:54:23.907] [28822,310461] [debug] 7ms, [6d92f0-c4ba-d843-9d86-3c6839a2bed362]: loading 137 CA certificates from Mozilla bundle. Update date: "Tue Jan 10 04:12:06 2023 GMT", SHA256: "fb1ecd641d0a02c01bc9036d513cb658bbda62a75e246bedbc01764560a639f0"
----

[{tabs}]
====
Couchbase Capella::
+
--
The Node.js SDK bundles Capella’s standard root certificate by default.
This means you don’t need any additional configuration to enable TLS -- simply use `couchbases://` in your connection string.

NOTE: Capella's root certificate is *not* signed by a well known CA (Certificate Authority).
However, as the certificate is bundled with the SDK, it is trusted by default.
--

Couchbase Server::
+
--
Certificates from the Mozilla Root CA store are now bundled with the SDK. 
If the server's certificate is signed by a well-known CA (e.g., GoDaddy, Verisign, etc.), you don't need to configure this in the `SecurityConfig` settings, instead use `couchbases://` in your connection string.

You can still provide a certificate explicitly if necessary:

. Get the CA certificate from the cluster and save it in a text file.
. Enable encryption on the client side and point it to the file containing the certificate.

It is important to make sure you are transferring the certificate in an encrypted manner from the server to the client side, so either copy it through SSH, or through a similar secure mechanism.

If you are running on `localhost` and just want to enable TLS for a development machine, just copying and pasting it suffices
-- _so long as you use `127.0.0.1` rather than `localhost` in the connection string_.
This is because the certificate will not match the name _localhost_.

// TODO: Not entirely sure this is correct, needs to be verified.
//Setting `TLSSkipVerify` is a workaround if you need to use `couchbases://localhost`.

Navigate in the admin UI to menu:Settings[Cluster] and copy the input box of the TLS certificate into a file on your machine (which we will refer to as `cluster.cert`).
It looks similar to this:

----
-----BEGIN CERTIFICATE-----
MIICmDCCAYKgAwIBAgIIE4FSjsc3nyIwCwYJKoZIhvcNAQEFMAwxCjAIBgNVBAMT
ASowHhcNMTMwMTAxMDAwMDAwWhcNNDkxMjMxMjM1OTU5WjAMMQowCAYDVQQDEwEq
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzz2I3Gi1XcOCNRVYwY5R
................................................................
mgDnQI8nw2arBRoseLpF6WNw22CawxHVOlMceQaGOW9gqKNBN948EvJJ55Dhl7qG
BQp8sR0J6BsSc86jItQtK9eQWRg62+/XsgVCmDjrB5owHPz+vZPYhsMWixVhLjPJ
mkzeUUj/kschgQ0BWT+N+pyKAFFafjwFYtD0e5NwFUUBfsOyQtYV9xu3fw+T2N8S
itfGtmmlEfaplVGzGPaG0Eyr53g5g2BgQbi5l5Tt2awqhd22WOVbCalABd9t2IoI
F4+FjEqAEIr1mQepDaNM0gEfVcgd2SzGhC3yhYFBAH//8W4DUot5ciEhoBs=
-----END CERTIFICATE-----
----

The next step is to enable encryption and pass it the path to the certificate file
(note the connection string scheme is `couchbases://` rather than the non-TLS `couchbase://`).
Additionally, you need to provide your `username` and `password`:

[source,javascript]
----
include::example$auth.js[tag=tls-cacert,indent=0]
----

If you want to verify it's actually working, you can use a tool like [.cmd]`tcpdump`.
For example, an unencrypted upsert request looks like this (using `sudo tcpdump -i lo0 -A -s 0 port 11210`):

----
E..e..@.@.............+......q{...#..Y.....
.E...Ey........9........................id{"key":"value"}
----

After enabling encryption, you cannot inspect the traffic in cleartext (same upsert request, but watched on port 11207
which is the default encrypted port):

----
E.....@.@.............+....Z.'yZ..#........
..... ...xuG.O=.#.........?.Q)8..D...S.W.4.-#....@7...^.Gk.4.t..C+......6..)}......N..m..o.3...d.,.     ...W.....U..
.%v.....4....m*...A.2I.1.&.*,6+..#..#.5
----
--
====


// == Using DNS SRV records

include::{version-common}@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv]

The Node.js SDK always tries to use the SRV records, if the connection string contains a single hostname and the feature is not disabled explicitly with connection string option `dnssrv=off`.

In case of successful resolution a message like this will be written at `INFO` level of debug logs:

----
44ms [I4ebdb48d23db23b6] {10474} [INFO] (instance - L:219) Found host node.example.com:11210 via DNS SRV
----

If the DNS SRV records could not be loaded properly you'll get an exception logged and the given hostname will be used as an A record lookup.

----
81ms [If1e0caf208c1ff41] {11763} [INFO] (instance - L:202) DNS SRV lookup failed: LCB_ERR_UNKNOWN_HOST (1049). Ignore this if not relying on DNS SRV records
----

include::{version-common}@sdk:shared:partial$managing-connections.adoc[tag=cloud]
