= N1QL Queries from the SDK
:navtitle: N1QL from the SDK
:page-topic-type: howto
:page-aliases: n1ql-query

[abstract]
You can query for documents in Couchbase using the N1QL query language, a language based on SQL, but designed for structured and flexible JSON documents. 
Querying can solve typical programming tasks such as finding a user profile by email address, Facebook login, or user ID.

Our query service uses N1QL, which will be fairly familiar to anyone who's used any dialect of SQL. 
xref:#additional-resources[Additional resources] for learning about N1QL are listed at the bottom of the page.

Before you get started you may wish to check out the xref:6.5@server:n1ql:n1ql-language-reference/index.adoc[N1QL intro page], or just dive in with a query against our travel-sample data set. 
To make a Bucket queryable, it must have at least one index defined. 
You can define a _primary_ index on a bucket. 
While not recommended for production, defining a primary index is useful for ad hoc queries that are great for exploring your data, the reason they are not recommended for production is that they enable a full-bucket scan.

Use xref:6.5@server:tools:cbq-shell.adoc[cbq], our interactive Query shell.
Open it, and enter the following:

[source,n1ql]
----
CREATE PRIMARY INDEX ON `travel-sample`
----

By replacing _travel-sample_ with a different Bucket, you can build an index on your bucket of choice.

NOTE: The default installation places cbq in `/opt/couchbase/bin/` on Linux, `/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/cbq` on OS X, and `C:\Program Files\Couchbase\Server\bin\cbq.exe` on Microsoft Windows.

// TODO: improving this and/or adding server/6.0/tools/query-workbench.html

== Queries & Placeholders

Placeholders allow you to specify variable constraints for an otherwise constant query. 
There are two variants of placeholders: positional and named parameters. 
Positional parameters use an ordinal placeholder for substitution and named parameters use variables. 
A named or positional parameter is a placeholder for a value in the WHERE, LIMIT, or OFFSET clause of a query. 
Note that both parameters and options are optional.

.Positional parameter example:
[source,javascript]
----
include::devguide:example$nodejs/n1ql-queries.js[tag=queryplaceholders,indent=0]
----

.Named parameter example:
[source,javascript]
----
include::devguide:example$nodejs/n1ql-queries.js[tag=querynamed,indent=0]
----

// The complete code for this page's example can be found at xref:[??]

== Handling Results

Most queries return more than one result, and you want to iterate over the results:
[source,javascript]
----
include::devguide:example$nodejs/n1ql-queries.js[tag=queryresults,indent=0]
----

//== Scan Consistency
//
//
//Setting a staleness parameter for queries, with `scan_consistency`, enables a tradeoff between latency and (eventual) consistency.

//* A N1QL query using the default *Not Bounded* Scan Consistency will not wait for any indexes to finish updating before running the query and returning results, meaning that results are returned quickly, but the query will not return any documents that are yet to be indexed.

//* With Scan Consistency set to *RequestPlus*, all document changes and index updates are processed before the query is run.
//Select this when consistency is always more important than performance.
//
//* For a middle ground, *AtPlus* is a 'read your own write' (RYOW) option, which means it just waits for the new documents that you specify to be indexed, rather than an entire index of multiple documents.
// See the xref:scan-consistency-examples.adoc[examples] for how to use *AtPlus* for the best performance balance for many circumstances.

// commented out until this is working - n1ql-queries.js
//.ScanConsisteny (RYOW)
//[source,javascript]
//----
// // create / update document (mutation)
//var upsertResult = await collection.upsert('id', {name: 'Mike', type: 'User'});
//
// // create mutation state from mutation results
//var state = couchbase.MutationState.from(upsertResult);
//
// use mutation state with query option
//var result = await cluster.query(
//    'SELECT x.* FROM `default` WHERE x.Type=$1',
//    ['User'], {
//        consistentWith: state,
//    });
//----

// commented out until this is working - n1ql-queries.js
//== Streaming Large Result Sets
//
//The Node.js SDK supports a number of methods for performing queries, all through the same interface.  If you await on the result, or utilize a callback to receive the results, the entire resultset will be downloaded and cached before being returned.  If you wish to stream the results, you can use the result as an event emitter in order to row-by-row process the results.  Using the event emitter prevents the SDK from needing to cache the rows internally, and allows you to stream the results.

//.Streaming
//[source,javascript]
//----
//var result = cluster.query(
//    'SELECT x.* FROM `default` WHERE x.Type="User"');
//result.on('row', (row) => {
//    // handle the row
//    var name = row.name;
//});
//result.on('end', (meta) => {
//    // finish processing and handle the meta
//});
//----

== Additional Resources

NOTE: N1QL is not the only query option in Couchbase. 
Be sure to check that your use case fits your selection of query service.

// For a deeper dive into N1QL from the SDK, refer to our xref:concept:[N1QL SDK concept doc].

The xref:6.5@server:n1ql:n1ql-language-reference/index.adoc[N1QL Language Reference] introduces up a complete guide to the N1QL language, including all of the latest additions.

The http://query.pub.couchbase.com/tutorial/#1[N1QL interactive tutorial] is a good introduction to the basics of N1QL use.

// Indexes / GSI links?

// SQL++ / Analytics.
