= Provisioning Cluster Resources
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters

[abstract]
Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
Common use cases are outlined here, more recherché use cases are covered in the https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc[API docs].

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Node.js SDK also comes with some convenience functionality for common Couchbase management requests.


Management operations in the SDK may be performed through several interfaces depending on the object:

* BucketManager -- `Cluster.buckets()`
* UserManager -- `Cluster.users()`
* QueryIndexManager -- `Cluster.queryIndexes()`
* AnalyticsIndexManager -- `Cluster.analyticsIndexes()`
* SearchIndexManager -- `Cluster.searchIndexes()`
* CollectionManager -- `Bucket.collections()`
* ViewIndexManager -- `Bucket.viewIndexes()`.

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `cluster.bucket(name)` before you can use cluster level managers.


== Creating and Removing Buckets

The `BucketManager` interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the `Cluster.buckets()` method.

[source,javascript]
----
include::examples$provisioning.js[tag=create-bucketmgr,indent=0]
----

The `CreateBucketSettings` and `BucketSettings` structs are used for creating and updating buckets, `BucketSettings` is also used for exposing information about existing buckets.

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]


Here is the list of parameters available:

|====
| Name | Description | Can be updated
| `name string` | The name of the bucket, required for creation. | false
| `flushEnabled boolean` | Enables flushing to be performed on this bucket (see the <<flushing>> section below). | true
| `replicaIndex boolean` | Whether or not to replicate indexes. | false
| `ramQuotaMB uint64` | How much memory should each node use for the bucket, required for creation. | true
| `numReplicas uint32` | The number of replicas to use for the bucket. | true
| `bucketType BucketType` | The type of the bucket, required for creation. | false
| `evictionPolicy EvictionPolicyType` | The type of the eviction to use for the bucket, defaults to `valueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `maxTTL time.Duration` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `compressionMode CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
|====

The following example creates a "hello" bucket:

[source,javascript]
----
include::examples$provisioning.js[tag=create-bucket,indent=0]
----

We can now get this bucket and update it to enable flush:

[source,javascript]
----
include::examples$provisioning.js[tag=update-bucket,indent=0]
----

Once you no longer need to use the bucket, you can remove it:

[source,javascript]
----
include::examples$provisioning.js[tag=remove-bucket,indent=0]
----


[#flushing]
== Flushing Buckets

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the `flush` method:


[source,javascript]
----
include::examples$provisioning.js[tag=flush-bucket,indent=0]
----

The `flush` operation may fail if the bucket does not have flush enabled, in that case it will return an error.


== Collection Management

This is a xref:6.5@server:developer-preview:collections/collections-overview.adoc[Developer Preview feature], see the https://docs.couchbase.com/sdk-api/couchbase-node-client/CollectionManager.html[API doc].


== Index Management

In general,you will rarely need to work with Index Managers from the SDK.
For those occasions when you do, please see the relevant API docs:

* QueryIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.5/QueryIndexManager.html[`Cluster.queryIndexes()`];
* AnalyticsIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.5/AnalyticsIndexManager.html[`Cluster.analyticsIndexes()`];
* SearchIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.5/SearchIndexManager.html[`Cluster.searchIndexes()`];
* ViewIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.5/ViewIndexManager.html[`Bucket.viewIndexes()`].

