= Compatibility
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2

include::partial$attributes.adoc[]

[abstract]
{description}

The Couchbase Node.js Client aims to run on any https://github.com/nodejs/Release[LTS version of Node.js] -- see the table below for <<node-js-version-compatibility,supported versions>>.


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Node.js SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,20,30,20"]
|===
| | SDK 2.6  | SDK 3.0, 3.1 | 3.2, 4.0 - 4.2

| *Server 6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0-7.2*
| *◎*
| *◎*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.


=== Capella Compatibility

The Node.js SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]


== Node.js Version Compatibility

The Couchbase Node.js SDK aims to support https://github.com/nodejs/Release[LTS] versions of Node.js.
The table below indicates the Node.js SDK version where support of an LTS version of Node.js was added.
Node.js versions that have reached their https://endoflife.date/nodejs[End-of-Life date] are not supported.

.Supported Node.js Versions
[cols="5,8,8"]
|===
| Node.js LTS Version | LTS Support EOL | Couchbase SDK Versions Supported

| 14
| until 2023-04-30
| from 3.0.2

| 16
| until 2023-09-11
| from 3.2.0

| 18
| until 2025-04-30
| from 4.2.5

| 20
| until 2026-04-30
| from 4.2.5

|===


== Platform Compatibility

The Node.js SDK is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 8;
* CentOS 7.
* Ubuntu (LTS): 18.04 (_Bionic_), 20.04 (_Focal_), & 22.04 (_Jammy_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux versions that have not reached https://alpinelinux.org/releases/[end-of-life support] (since Node.js SDK 3.2.5). 
Note that while Alpine _might_ provide support upon request for older versions, any version that has reached end-of-life support is outside the scope of Couchbase technical support.

[discrete]
=== Microsoft Windows

Windows 10.
Any MS-supported version compatible with Visual Studio 2022 (VC17) or later.

[discrete]
=== Mac OS X

The current and previous two releases of OS X on both Intel and ARM.
At time of writing (October 2022): 13 (Ventura), 12 (Monterey), and 11 (Big Sur).
M1 ARM  architecture is fully supported in the Node.js SDK.
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

=== ARM Processor Support

AWS Amazon Graviton2, Apple M1 ARM processors, and ARMv8 on Ubuntu 20.04 (from SDK 4.2).


== Integrations

=== Ottoman ODM

https://ottomanjs.com/#introduction[Ottoman.js] version 2.3.0 and above are compatible with Couchbase Node.js SDK 4.2.0 and above.
Earlier versions of Ottoman ODM 2.x are only compatible with the 3.2 Node.js SDK.

== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="6,6,6"]
|===
| | Server 6.6 | Server 7.0 & 7.1

| Enhanced Durability
2+| All SDK versions

| Durable Writes
2+| Since 3.0

| Analytics
2+| Since 2.6

| Collections
| Developer Preview in 6.6, SDK 3.0
| Since 3.0.7

| Scope-Level {sqlpp} (formerly N1QL) Queries & all Collections features
| Not Supported
| Since SDK 3.2.0

| Field Level Encryption v2
2+| Since SDK 3.2.0footnote:[Field Level Encryption distributed as separate library.]

| Request Tracing
2+| Since SDK 3.2.0

| Distributed ACID Transactions
2+| Since Couchbase Server 6.6.1 and SDK 4.0

|===

include::{version-common}@sdk:shared:partial$network-requirements.adoc[]

[NOTE]
.Binary Size
====
You may find the binary of the SDK from version 4.0.0 to 4.2.4 too large to run in some environments.
If you cannot upgrade to 4.2.5 onwards for your app, 
the size can be drastically reduced, prior to zipping up the application, by running `strip` against it to remove the debug symbols:
[source,console]
----
strip --strip-debug
----
See the `strip` manpage for further details.
You can also safely remove the `src/` and `deps/` folders (under `node_modules/couchbase/`).
The 4.2.5 version of the SDK can provide recommendations on further reducing the size of the deployment package.
See https://github.com/couchbase/couchnode#aws-lambda[README] for details.
====

include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
