= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Node.js SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features

include::partial$attributes.adoc[]

[abstract]
{description}

The Couchbase Node.js Client will run on any https://github.com/nodejs/Release[supported LTS version of Node.js] -- currently, 12.x, 14.x, and 16.x.


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Node.js SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,20,30,20"]
|===
| | SDK 2.6  | SDK 3.0, 3.1 | 3.2, 4.0

| *Server 6.0*
| *✔*
| *✔*
| *✔*

| *Server 6.5-6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0*
| *◎*
| *◎*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.


== Platform Compatibility

The Node.js SDK is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 8;
* CentOS 7.
* Ubuntu (LTS) 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).

[discrete]
=== Microsoft Windows

We provide "prebuilds" for Windows 8.
Any MS-supported version compatible with Visual Studio 2022 (VC17) 

[discrete]
=== Mac OS X

The current and previous two releases of OS X on both Intel and ARM.
At time of writing (February 2022): 10.15 (_Catalina_), 11 (_Big Sur_), and 12 (_Monterey_).
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.


== Integrations

=== Ottoman ODM

The 3.2 Node.js SDK is compatible with https://ottomanjs.com/#introduction[version 2.0 of the Ottoman ODM].

NOTE: the 4.0 Node.js SDK is not tested against Ottoman.
We intend to support it fully in later versions.

== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,5,6,5"]
|===
| | Server 6.0 | Server 6.5 & 6.6 | Server 7.0

| Enhanced Durability
3+| All SDK versions

| Durable Writes
1+| Not Supported
2+| Since 3.0

| Analytics
3+| Since 2.6

| Default Collections
| Not Supported
| Developer Preview in 6.5-6.6, SDK 3.0
| Since 3.0.7

| Scope-Level N1QL Queries & all Collections features
2+| Not Supported
| Since SDK 3.2.0

| Field Level Encryption v2
| Not Supported
2+| Since SDK 3.2.0footnote:[Field Level Encryption distributed as separate library.]

| Request Tracing
| Not Supported
2+| Since SDK 3.2.0
|===

include::{version-server}@sdk:shared:partial$network-requirements.adoc[]


include::{version-server}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


include::7.0@sdk:shared:partial$api-version.adoc[tag=api-version]
