= Ottoman ODM Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Ottoman ODM.
:navtitle: Release Notes
:page-topic-type: project-doc

[abstract]
{description}

These pages cover the 2._x_ versions of the Ottoman ODM. 

The Ottoman ODM will run on any https://github.com/nodejs/Release[supported LTS version of Node.js].



== Support in Node.js SDK 4.0

Ottoman is currently *not supported* in Node.js SDK 4.0 & 4.1.
We intend to fully support it with the next 4.2 release.

In the meantime, if you are interested in checking out Ottoman, 
please read the xref:3.2@nodejs-sdk:hello-world:start-using-ottoman.adoc[Ottoman for Node.js SDK 3.2] page.


== Version 2.2.1 (22 June 2022)

Version 2.2.1 is a patch release of the Ottoman ODM.
This release adds minor fixes, and a number of dependency upgrades.

[source,console]
----
$ npm install ottoman@2.2.1
----

https://ottomanjs.com/#installation[Ottoman installation]

=== Fixed Issues

* Updated index naming to include the model's name.

* `options.strict` is now set to true by default.

* A `DocumentNotFound` error is thrown for documents with a different model.

* Updated regex to ensure a clean index name.


== Version 2.2.0 (29 March 2022)

Version 2.2.0 is a minor release of the Ottoman ODM. 
This release adds two new features, and a number of dependency upgrades.

[source,console]
----
$ npm install ottoman@2.2.0
----

https://ottomanjs.com/#installation[Ottoman installation]

=== New Features

* Ottoman: added support to allow `modelKey` to be a nested field.

* Hooks: trigger embed schema hooks.


== Version 2.1.0 (7 Feb 2022)

Version 2.1.0 is a minor release of the Ottoman Object Document Mapper(ODM) library, bringing a number of improvements, and support for Couchbase Node.js SDK 3.2.4.

[source,console]
----
$ npm install ottoman@2.1.0
----

https://ottomanjs.com/#installation[Ottoman installation]

=== New Features

* Added ability to set `keyGeneratorDelimiter` to an empty string to use ID as key with no delimiter.

* Updated Couchbase Node.js SDK to version 3.2.4.

=== Fixed Issues

* Fixed model inconsistency in find method.

* Bumped `shelljs` and `follow-redirects` dependencies.

=== Documentation Fixes

* Reword v1 docs note.


== Version 2.0.0 (30 Sept 2021)

This is the first GA release of the Ottoman Object Document Mapper(ODM) library.

[source,console]
----
$ npm install ottoman@2.0.0
----

https://ottomanjs.com/#installation[Ottoman page]

=== New Features

* Exposed various SDK types to use directly from Ottoman.

* Added start option `ignoreWatchIndexes`. The `start()` function will wait for indexes by default, but this can be disabled by setting `ignoreWatchIndexes` to true.

* Enforced referenced document option.

* Ottoman now returns the document id reference if it doesn't exist.

* Added event to listen for index readiness.

* Added examples for find methods and bulk operations.

* Improved from clause value escape behavior in the QueryBuilder.

* Upgraded embedded Couchbase SDK to version `3.2.2`.

=== Fixed Issues

* Refactored lean and populate code.

* Fixed broken links.

* Fixed model links for statics methods.

=== Documentation Fixes

* Fixed typo in the major word.

* Updated quickstart example.

* Updated getting started example.

* Updated docs for async connect function.

* Added metrics to Ottoman vs NodeJS SDK documentation.

* Updated FAQ benefits section.

* Fixed broken links to new sdk docs.

* Downgraded typedoc.

* Added api documentation for namespace.

* Update FAQ page.
