= Couchbase Node.js Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-nodejs-sdk,ROOT:release-notes,ROOT:sdk-release-notes

[abstract]
Release notes, installation instructions, and download archive for the Couchbase Node.js Client.

These pages cover the 3.0 versions of the Couchbase Node.js SDK. 
For release notes, download links, and installation methods for 2.6 and earlier releases of the Couchbase Node.js Client, please see the xref:2.6@nodejs-sdk::sdk-release-notes.adoc[2.x Node.js Release Notes & Download Archive].

// include::hello-world:start-using-sdk.adoc[tag=prep]

// include::hello-world:start-using-sdk.adoc[tag=install]

To install an older version, specify the version directly with npm. 
For example, to install version 2.6.1:

[source,bash]
----
npm install couchbase@2.6.1
----

== Version 3.0.0-beta.1 (Oct 3 2019)

[source,bash]
----
$ npm install couchbase@3.0.0-beta.1
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.0-beta.1/[API Reference]

=== New Features

* Updated to 3.0.0-beta.1 release of libcouchbase.
* Added support for checking the existence of a document.
* Added support for per-operation transcoders.
* Implemented data-structures support.
* Implemented bucket management APIs.
* Implemented full view management APIs.
* Implemented diagnostics APIs
* Implemented debug-based logging.
* Added contextual details to errors returned from the library.

=== Fixed Issues

* Updated all dependencies based on security audit.
* Improved connection management.
* Adjusted geospatial coordinate ordering to lon/lat rather than lat/lon.
* Fixed bugs causing sub-document operations to sometimes fail.
* Fixed issues causing unreliable query service error types.
* Removed support for spatial views.

== Version 3.0.0-alpha.1 (May 2 2019)

This is the first pre-release of the third generation Node.js SDK and a complete rewrite over the 2.x series. 
As such, there are no release notes for this first alpha release.
