= Couchbase Node.js Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-nodejs-sdk,ROOT:release-notes,ROOT:sdk-release-notes

[abstract]
Release notes, installation instructions, and download archive for the Couchbase Node.js Client.

These pages cover the 3.0 versions of the Couchbase Node.js SDK. 
For release notes, download links, and installation methods for 2.6 and earlier releases of the Couchbase Node.js Client, please see the xref:2.6@nodejs-sdk::sdk-release-notes.adoc[2.x Node.js Release Notes & Download Archive].

The Couchbase Node.js Client will run on any https://github.com/nodejs/Release[supported LTS version of Node.js] -- currently, 10.x, and 12.x.

// include::hello-world:start-using-sdk.adoc[tag=prep]

// include::hello-world:start-using-sdk.adoc[tag=install]

To install an older version, specify the version directly with npm. 
For example, to install version 2.6.1:

[source,console]
----
$ npm install couchbase@2.6.1
----


== Version 3.0.5 (6 August 2020)

Version 3.0.5 is a release of the third generation Node.js SDK.

[source,console]
----
$ npm install couchbase@3.0.5
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.5/[API Reference]

=== Fixed Issues

* Updated all dependencies to latest versions.
* Various minor documentation fixes.


== Version 3.0.4 (17 June 2020)

Version 3.0.4 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.4
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.4/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Fixed binary data being interpreted as UTF-8.


== Version 3.0.3 (14 June 2020)

Version 3.0.3 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.3
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.3/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-702[JSCBC-702]:
Fixed MaxExpiry not being specifiable when creating a collection.
* http://issues.couchbase.com/browse/JSCBC-757[JSCBC-757]:
Fixed CreateCollection parameters not matching specification.
* http://issues.couchbase.com/browse/JSCBC-698[JSCBC-698]:
Fixed MutateIn placeholders not being handled correctly.
* http://issues.couchbase.com/browse/JSCBC-751[JSCBC-751]:
Fixed documentation of SearchIndexManager.
* http://issues.couchbase.com/browse/JSCBC-754[JSCBC-754]:
Don't swap in a bucket name when none is used.
* Updated all dependencies to latest versions.
* Updated to libcouchbase 3.0.2
* Various other minor fixes.

=== Known Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Buffer objects containing non-UTF8 data can become mangled when inserting them into a bucket or collection.  
This has been corrected in 3.0.4.


== Version 3.0.2 (7 May 2020)

Version 3.0.2 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.2
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.2/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-715[JSCBC-715]:
Fixed issue with sending highlight option with Search queries.
* http://issues.couchbase.com/browse/JSCBC-727[JSCBC-727]:
Fixed views API to use correct casing on parameter names.
* http://issues.couchbase.com/browse/JSCBC-676[JSCBC-676]:
Fixed view queries to return expected row object data.
* http://issues.couchbase.com/browse/JSCBC-728[JSCBC-728]:
Fixed user management sometimes failing to deserialize users.
* http://issues.couchbase.com/browse/JSCBC-729[JSCBC-729]:
Fixed user management user upsert not sending roles.
* http://issues.couchbase.com/browse/JSCBC-730[JSCBC-730]:
Fixed lookupIn method to return content not results.
* http://issues.couchbase.com/browse/JSCBC-714[JSCBC-714]:
Fixed mutateIn not including counter results in return object.
* http://issues.couchbase.com/browse/JSCBC-700[JSCBC-700]:
Fixed issue with analytics named parameters causing query failures.
* http://issues.couchbase.com/browse/JSCBC-701[JSCBC-701]:
Fixed custom search query timeouts causing query failures.
* Updated all dependencies to latest versions.
* Updated to libcouchbase 3.0.1
* Various other minor fixes.

=== Known Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Buffer objects containing non-UTF8 data can become mangled when inserting them into a bucket or collection.  
This has been corrected in 3.0.4.


== Version 3.0.1 (20 March 2020)

Version 3.0.1 is the second release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.1
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.1/[API Reference]

=== New Features

* Updated to libcouchbase 3.0.1

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-669[JSCBC-669]:
Fixed CAS not being returned in some cases.
* http://issues.couchbase.com/browse/JSCBC-682[JSCBC-682]:
Fixed N1QL parameter options parsing.
* http://issues.couchbase.com/browse/JSCBC-666[JSCBC-666]:
Fixed ConjunctionSearchQuery not being able to add queries.
* http://issues.couchbase.com/browse/JSCBC-665[JSCBC-665]:
Fixed search query not using the correct indexes.
* http://issues.couchbase.com/browse/JSCBC-677[JSCBC-677]:
Fixed search query consistency not being set in some cases.
* http://issues.couchbase.com/browse/JSCBC-668[JSCBC-668]:
Fixed an UnhandledPromiseRejection error which could occur.
* http://issues.couchbase.com/browse/JSCBC-673[JSCBC-673]:
Improved handling of cluster closing.
* http://issues.couchbase.com/browse/JSCBC-711[JSCBC-711]:
Fixed a case where closing connections could trigger a segfault.
* http://issues.couchbase.com/browse/JSCBC-695[JSCBC-695]:
Fixed issue with the use of custom connection string options.
* http://issues.couchbase.com/browse/JSCBC-683[JSCBC-683]:
Fixed inconsistent metrics data from query service.
* Updated to latest version of all dependencies.
* Adjusted prebuilt binaries to match currently support Node.js versions.

=== Known Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Buffer objects containing non-UTF8 data can become mangled when inserting them into a bucket or collection.  
This has been corrected in 3.0.4.


== Version 3.0.0 (20 January 2020)

This is the first GA release of the third generation Node.js SDK.

[source,console]
----
$ npm install couchbase@3.0.0
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.0/[API Reference]

=== New Features

* Updated to libcouchbase 3.0.0

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-653[JSCBC-653]:
Fixed transcoding in getReplica and getAndTouch.
* http://issues.couchbase.com/browse/JSCBC-650[JSCBC-650]:
Improved stream wrappers to support both events and async/await.
* http://issues.couchbase.com/browse/JSCBC-657[JSCBC-657]:
Fixed some error double-translation issues.
* http://issues.couchbase.com/browse/JSCBC-652[JSCBC-652]:
Fixed issue with data structures exist checks.
* http://issues.couchbase.com/browse/JSCBC-655[JSCBC-655]:
Fixed search query constructors not being exported.
* http://issues.couchbase.com/browse/JSCBC-656[JSCBC-656]:
Renamed QueryProfile to QueryProfileMode.
* http://issues.couchbase.com/browse/JSCBC-639[JSCBC-639]:
Updated tests to reflect updated libcouchbase behaviour.
* http://issues.couchbase.com/browse/JSCBC-654[JSCBC-654]:
Updated to the latest mock to resolve test issue.
* http://issues.couchbase.com/browse/JSCBC-647[JSCBC-647]:
Marked all error contexts as uncommitted.
* http://issues.couchbase.com/browse/JSCBC-596[JSCBC-596]:
Marked defaultScope, scope, and collection methods uncommitted.

=== Known Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Buffer objects containing non-UTF8 data can become mangled when inserting them into a bucket or collection.  
This has been corrected in 3.0.4.


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 3.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
