= Couchbase Node.js Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-nodejs-sdk,ROOT:release-notes,ROOT:sdk-release-notes

[abstract]
Release notes, installation instructions, and download archive for the Couchbase Node.js Client.

These pages cover the 3.0 versions of the Couchbase Node.js SDK. 
For release notes, download links, and installation methods for 2.6 and earlier releases of the Couchbase Node.js Client, please see the xref:2.6@nodejs-sdk::sdk-release-notes.adoc[2.x Node.js Release Notes & Download Archive].

// include::hello-world:start-using-sdk.adoc[tag=prep]

// include::hello-world:start-using-sdk.adoc[tag=install]

To install an older version, specify the version directly with npm. 
For example, to install version 2.6.1:

[source,bash]
----
npm install couchbase@2.6.1
----

== Version 3.0.0 (Oct 3 2019)

[source,bash]
----
$ npm install couchbase@3.0.0
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.0-beta.1/[API Reference]

=== New Features

* Updated to libcouchbase 3.0.0

=== Fixed Issues

Fixed Issues:
* http://issues.couchbase.com/browse/JSCBC-653[JSCBC-653]:
Fixed transcoding in getReplica and getAndTouch.
* http://issues.couchbase.com/browse/JSCBC-650[JSCBC-650]:
Improved stream wrappers to support both events and async/await.
* http://issues.couchbase.com/browse/JSCBC-657[JSCBC-657]:
Fixed some error double-translation issues.
* http://issues.couchbase.com/browse/JSCBC-652[JSCBC-652]:
Fixed issue with data structures exist checks.
* http://issues.couchbase.com/browse/JSCBC-655[JSCBC-655]:
Fixed search query constructors not being exported.
* http://issues.couchbase.com/browse/JSCBC-656[JSCBC-656]:
Renamed QueryProfile to QueryProfileMode.
* http://issues.couchbase.com/browse/JSCBC-639[JSCBC-639]:
Updated tests to reflect updated libcouchbase behaviour.
* http://issues.couchbase.com/browse/JSCBC-654[JSCBC-654]:
Updated to the latest mock to resolve test issue.
* http://issues.couchbase.com/browse/JSCBC-647[JSCBC-647]:
Marked all error contexts as uncommitted.
* http://issues.couchbase.com/browse/JSCBC-596[JSCBC-596]:
Marked defaultScope, scope, and collection methods uncommitted.


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 3.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].
