= Couchbase Node.js Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Couchbase Node.js Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-nodejs-sdk,ROOT:release-notes,ROOT:sdk-release-notes

// tag::all[]
[abstract]
{description}

These pages cover the 3._x_ versions of the Couchbase Node.js SDK. 
For release notes, download links, and installation methods for 2.6 and earlier releases of the Couchbase Node.js Client, please see the xref:2.6@nodejs-sdk::sdk-release-notes.adoc[2.x Node.js Release Notes & Download Archive].

The Couchbase Node.js Client will run on any https://github.com/nodejs/Release[supported LTS version of Node.js] -- currently, 10.x, and 12.x.

// include::hello-world:start-using-sdk.adoc[tag=prep]

// include::hello-world:start-using-sdk.adoc[tag=install]

To install an older version, specify the version directly with npm. 
For example, to install version 2.6.1:

[source,console]
----
$ npm install couchbase@2.6.1
----


== Version 3.2.2 (16 Sept 2021)

Version 3.2.2 is the next minor release of the third generation Node.js SDK, bringing a number of improvements.

[source,console]
----
$ npm install couchbase@3.2.2
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-3.2.2/modules.html[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-805[JSCBC-805]:
Users can now manage the Couchbase Eventing Service from the Node.js SDK client.
* http://issues.couchbase.com/browse/JSCBC-894[JSCBC-894]:
Updated SSL failure error messaging to improve debugging experience.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-937[JSCBC-937]:
Fixed segfault during connection GC.
* http://issues.couchbase.com/browse/JSCBC-938[JSCBC-938]:
Fixed segfault during v8 interpreter shutdown.
* http://issues.couchbase.com/browse/JSCBC-939[JSCBC-939]:
Fixed segfault related to logging after shutdown.
* http://issues.couchbase.com/browse/JSCBC-949[JSCBC-949]:
Fixed query getAllIndexes and watchIndexes to work with collection indexes.
* http://issues.couchbase.com/browse/JSCBC-948[JSCBC-948]:
Corrected issue with diagnostics calls failing on brand new connections.
* http://issues.couchbase.com/browse/JSCBC-945[JSCBC-945]:
Fixed some methods failing to parse optional callbacks correctly.
* Updated libcouchbase to include the following fixes: 
https://issues.couchbase.com/browse/CCBC-1494[CCBC-1494], https://issues.couchbase.com/browse/CCBC-1487[CCBC-1487], https://issues.couchbase.com/browse/CCBC-1488[CCBC-1488].



== Version 3.2.1 (26 Aug 2021)

Version 3.2.1 is the next minor release of the third generation Node.js SDK, bringing a number of improvements.

[source,console]
----
$ npm install couchbase@3.2.1
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-3.2.1/modules.html[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-744[JSCBC-744]:
Added support for worker threads.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-910[JSCBC-910]:
Fixed segfault on connection GC.
* http://issues.couchbase.com/browse/JSCBC-933[JSCBC-933]:
Fixed issue with null/undefined logger callbacks.
* http://issues.couchbase.com/browse/JSCBC-918[JSCBC-918]:
Fixed issue with `watchIndexes` not returning.
* http://issues.couchbase.com/browse/JSCBC-913[JSCBC-913]:
Fixed issue with incorrect role names being returned from user management APIs.
* http://issues.couchbase.com/browse/JSCBC-911[JSCBC-911]:
Fixed `MutateInSpec.insert` options not being optional.
* http://issues.couchbase.com/browse/JSCBC-905[JSCBC-905]:
Fixed drop collection returning `FeatureNotAvailable` in error.
* Updated all dependencies to latest versions.
* Updated to libcouchbase 3.2.1.



== Version 3.2.0 (21 July 2021)

Version 3.2.0 is the next minor release of the third generation Node.js SDK, bringing a number of improvements.

[source,console]
----
$ npm install couchbase@3.2.0
----

https://docs.couchbase.com/sdk-api/couchbase-node-client-3.2.0/modules.html[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-883[JSCBC-883]:
Reimplemented the library with TypeScript.
* http://issues.couchbase.com/browse/JSCBC-806[JSCBC-806]:
Added ability to specify collections to search query.
* http://issues.couchbase.com/browse/JSCBC-886[JSCBC-886]:
Added ability to specify raw search query options.
* http://issues.couchbase.com/browse/JSCBC-770[JSCBC-770]/
  http://issues.couchbase.com/browse/JSCBC-838[JSCBC-838]:
Implemented metrics and tracing.
* http://issues.couchbase.com/browse/JSCBC-707[JSCBC-707]:
Added test to confirm query streaming works properly.
* http://issues.couchbase.com/browse/JSCBC-900[JSCBC-900]:
Fixed issue with some search query options.
* http://issues.couchbase.com/browse/JSCBC-901[JSCBC-901]:
Added workaround for deferring HTTP operations.
* http://issues.couchbase.com/browse/JSCBC-858[JSCBC-858]:
Fixed issue where FeatureNotAvailable was thrown in error.
* http://issues.couchbase.com/browse/JSCBC-903[JSCBC-903]:
Fixed issue with incorrect subdocument macro value.
* http://issues.couchbase.com/browse/JSCBC-832[JSCBC-832]:
Implemented preserveExpiry functionality.
* http://issues.couchbase.com/browse/JSCBC-762[JSCBC-762]:
Added support for managing analytics remote links.
* http://issues.couchbase.com/browse/JSCBC-763[JSCBC-763]:
Added support for compound data-verse names.


=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-870[JSCBC-870]:
Updated mutateIn to use StoreSemantics.
* http://issues.couchbase.com/browse/JSCBC-876[JSCBC-876]:
Fixed BucketSettings evictionPolicy naming.
* http://issues.couchbase.com/browse/JSCBC-871[JSCBC-871]:
Fixed issue where unhandled exceptions could be thrown.
* http://issues.couchbase.com/browse/JSCBC-860[JSCBC-860]:
Fixed issue with flushEnabled not being retrieved correctly.
* http://issues.couchbase.com/browse/JSCBC-829[JSCBC-829]:
Fixed segfault on failed management operations.
* http://issues.couchbase.com/browse/JSCBC-825[JSCBC-825]:
Fixed definition of search facets in queries.
* http://issues.couchbase.com/browse/JSCBC-873[JSCBC-873]:
Renamed GetResult.expiry to GetResult.expiryTime to match spec.
* http://issues.couchbase.com/browse/JSCBC-869[JSCBC-869]:
Updated Unlock not to return a Result, it is never valid.
* http://issues.couchbase.com/browse/JSCBC-872[JSCBC-872]:
Updated CouchbaseSet remove to use the correct CAS.
* http://issues.couchbase.com/browse/JSCBC-875[JSCBC-875]:
Fixed watchIndexes using the wrong argument number.
* http://issues.couchbase.com/browse/JSCBC-836[JSCBC-836]:
Fixed property name for configuring bucket replica count.
* http://issues.couchbase.com/browse/JSCBC-863[JSCBC-863]:
Added additional tests for cas mismatch errors.
* http://issues.couchbase.com/browse/JSCBC-864[JSCBC-864]:
Fixed issue with error handling in LookupIn and MutateIn.
* http://issues.couchbase.com/browse/JSCBC-862[JSCBC-862]:
Fixed export typo causing failed query index manager construction.
* http://issues.couchbase.com/browse/JSCBC-882[JSCBC-882]:
Added missing getAllScopes method to CollectionManager.
* http://issues.couchbase.com/browse/JSCBC-811[JSCBC-811]:
Updated scopes/collections APIs to match latest specification.
* Added deprecation warning to calling Cluster constructor.
* Fixed deprecation warning caused by callback invocation.
* Added Mac arm64 config to allow test builds with M1.
* Fixed issue where bucket manager tests would fail in error.
* Fixed issue with test cleanup handling.
* Refactored LookupInMacro / MutateInMacro to work better with TypeScript.
* Fixed HTTP errors not containing context in some cases.
* Fixed some IndexMissing errors appearing as undefined errors.
* Fixed UserManager parsing of User objects.
* Fixed UserManager parsing of ldapGroupReference field.
* Fixed chaining of the MutationState.add method.
* Refactored all tests to properly pass lint checks with Typescript.
* Rewrote documentation to integrate with Typescript.
* Switched to using typedoc rather than jsdoc.
* Deprecated Node.js 8 support as it is now EOL.
* Updated all dependencies to latest versions.
* Updated to the latest Typescript version.
* Updated to libcouchbase 3.2.0.


== Version 3.1.3 (5 May 2021)

Version 3.1.3 is a patch release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.1.3
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.1.3/[API Reference]

=== Fixed Issues
* http://issues.couchbase.com/browse/JSCBC-884[JSCBC-884]:
Fixed a number of memory access issues.
* http://issues.couchbase.com/browse/JSCBC-881[JSCBC-881]:
Fixed memory leak due to missing cell dereferences.
* Updated to libcouchbase 3.1.2.
* Updated all dependencies to latest versions.


== Version 3.1.2 (9 April 2021)

Version 3.1.2 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.1.2
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.1.2/[API Reference]

=== Fixed Issues
* http://issues.couchbase.com/browse/JSCBC-856[JSCBC-856]:
Fixed memory leak with trace span management.
* http://issues.couchbase.com/browse/JSCBC-850[JSCBC-850]:
Fixed some connection options not propagating to bucket connections.
* http://issues.couchbase.com/browse/JSCBC-849[JSCBC-849]:
Fixed some query errors returning the incorrect errors.
* Updated to libcouchbase 3.1.0.
* Updated all dependencies to latest versions.


== Version 3.1.1 (13 January 2021)

Version 3.1.1 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.1.1
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.1.1/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-835[JSCBC-835]:
Deprecated maxTTL in favor of maxExpiry.
* http://issues.couchbase.com/browse/JSCBC-834[JSCBC-834]:
Fixed createCollection not working with default expiry.
* http://issues.couchbase.com/browse/JSCBC-824[JSCBC-824]:
Added missing options docs for Increment/Decrement.
* http://issues.couchbase.com/browse/JSCBC-828[JSCBC-828]:
Fixed view-query 0 limit queries.
* http://issues.couchbase.com/browse/JSCBC-823[JSCBC-823]:
Fixed serialization of views docid fields.
* http://issues.couchbase.com/browse/JSCBC-822[JSCBC-822]:
Fixed view ordering behaviour.
* Updated to libcouchbase 3.0.7.
* Updated all dependencies to latest versions.


== Version 3.1.0 (2 December 2020)

Version 3.1.0 is a minor release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release, 
and adding features to support Couchbase Server 6.6.

[source,console]
----
$ npm install couchbase@3.1.0
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.1.0/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-761[JSCBC-761]:
Added support for specifying minimum bucket durability.
* http://issues.couchbase.com/browse/JSCBC-787[JSCBC-787]:
Added option to disable search scoring.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-820[JSCBC-820]:
Reduced calls to debug.extend.
* http://issues.couchbase.com/browse/JSCBC-772[JSCBC-772]:
Added missing partition information to query indexes.
* http://issues.couchbase.com/browse/JSCBC-818[JSCBC-818]:
Fixed issue where analytics query context was not sent.
* http://issues.couchbase.com/browse/JSCBC-812[JSCBC-812]:
Updated CollectionManager to throw errors when collections are not supported.
* http://issues.couchbase.com/browse/JSCBC-816[JSCBC-816]:
Fix cluster errors not propagating for http methods.
* http://issues.couchbase.com/browse/JSCBC-815[JSCBC-815]:
Fixed seg-fault due to re-using consumed va_list.
* Various documentation updates.
* Updated typescript definitions file.
* Updated all dependencies to latest versions.


== Version 3.0.7 (6 November 2020)

Version 3.0.7 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.7
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.7/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-773[JSCBC-773]:
Added query collections support.
* http://issues.couchbase.com/browse/JSCBC-803[JSCBC-803]:
Added support for pinging at a cluster level.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-692[JSCBC-692]:
Updated transcoders to bubble errors.
* http://issues.couchbase.com/browse/JSCBC-799[JSCBC-799]:
Improved error handling for deferred operations.
* http://issues.couchbase.com/browse/JSCBC-756[JSCBC-756]:
Updated xattr helpers to be consistent.
* http://issues.couchbase.com/browse/JSCBC-755[JSCBC-755]:
Added support for multi-value sub-document array ops.
* http://issues.couchbase.com/browse/JSCBC-821[JSCBC-821]:
Added missing MutationState implementation.
* http://issues.couchbase.com/browse/JSCBC-797[JSCBC-797]:
Resolved a number of typescript typings errors.
* http://issues.couchbase.com/browse/JSCBC-724[JSCBC-724]:
Added a test case to confirm queries also cancel.
* Added docs and types generation to `make check`.
* Various minor documentation updates.
* Updated to libcouchbase 3.0.6
* Updated all dependencies to latest versions.


== Version 3.0.6 (3 September 2020)

Version 3.0.6 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.6
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.6/[API Reference]

=== New Features

* http://issues.couchbase.com/browse/JSCBC-786[JSCBC-786]:
Added uncommitted collections support for user management.
* http://issues.couchbase.com/browse/JSCBC-743[JSCBC-743]:
Added high-level options for basic configuration.
* http://issues.couchbase.com/browse/JSCBC-788[JSCBC-788]:
Added high-level options for specifying certificates.
* http://issues.couchbase.com/browse/JSCBC-686[JSCBC-686]:
Added auto generation of TypeScript types using JSDoc.

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-784[JSCBC-784]:
Fixed some results using value instead of content.
* http://issues.couchbase.com/browse/JSCBC-758[JSCBC-758]:
Improved view scan consistency handling.
* Updated to libcouchbase 3.0.4.
* Updated all dependencies to latest versions.
* Various minor documentation updates.
* Various other minor fixes.


== Version 3.0.5 (6 August 2020)

Version 3.0.5 is a release of the third generation Node.js SDK.

[source,console]
----
$ npm install couchbase@3.0.5
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.5/[API Reference]

=== Fixed Issues

* Updated all dependencies to latest versions.
* Various minor documentation fixes.


== Version 3.0.4 (17 June 2020)

Version 3.0.4 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.4
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.4/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Fixed binary data being interpreted as UTF-8.


== Version 3.0.3 (14 June 2020)

Version 3.0.3 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.3
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.3/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-702[JSCBC-702]:
Fixed MaxExpiry not being specifiable when creating a collection.
* http://issues.couchbase.com/browse/JSCBC-757[JSCBC-757]:
Fixed CreateCollection parameters not matching specification.
* http://issues.couchbase.com/browse/JSCBC-698[JSCBC-698]:
Fixed MutateIn placeholders not being handled correctly.
* http://issues.couchbase.com/browse/JSCBC-751[JSCBC-751]:
Fixed documentation of SearchIndexManager.
* http://issues.couchbase.com/browse/JSCBC-754[JSCBC-754]:
Don't swap in a bucket name when none is used.
* Updated all dependencies to latest versions.
* Updated to libcouchbase 3.0.2
* Various other minor fixes.

=== Known Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Buffer objects containing non-UTF8 data can become mangled when inserting them into a bucket or collection.  
This has been corrected in 3.0.4.


== Version 3.0.2 (7 May 2020)

Version 3.0.2 is a release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.2
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.2/[API Reference]

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-715[JSCBC-715]:
Fixed issue with sending highlight option with Search queries.
* http://issues.couchbase.com/browse/JSCBC-727[JSCBC-727]:
Fixed views API to use correct casing on parameter names.
* http://issues.couchbase.com/browse/JSCBC-676[JSCBC-676]:
Fixed view queries to return expected row object data.
* http://issues.couchbase.com/browse/JSCBC-728[JSCBC-728]:
Fixed user management sometimes failing to deserialize users.
* http://issues.couchbase.com/browse/JSCBC-729[JSCBC-729]:
Fixed user management user upsert not sending roles.
* http://issues.couchbase.com/browse/JSCBC-730[JSCBC-730]:
Fixed lookupIn method to return content not results.
* http://issues.couchbase.com/browse/JSCBC-714[JSCBC-714]:
Fixed mutateIn not including counter results in return object.
* http://issues.couchbase.com/browse/JSCBC-700[JSCBC-700]:
Fixed issue with analytics named parameters causing query failures.
* http://issues.couchbase.com/browse/JSCBC-701[JSCBC-701]:
Fixed custom search query timeouts causing query failures.
* Updated all dependencies to latest versions.
* Updated to libcouchbase 3.0.1
* Various other minor fixes.

=== Known Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Buffer objects containing non-UTF8 data can become mangled when inserting them into a bucket or collection.  
This has been corrected in 3.0.4.


== Version 3.0.1 (20 March 2020)

Version 3.0.1 is the second release of the third generation Node.js SDK, bringing enhancements and bugfixes over the last stable release.

[source,console]
----
$ npm install couchbase@3.0.1
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.1/[API Reference]

=== New Features

* Updated to libcouchbase 3.0.1

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-669[JSCBC-669]:
Fixed CAS not being returned in some cases.
* http://issues.couchbase.com/browse/JSCBC-682[JSCBC-682]:
Fixed N1QL parameter options parsing.
* http://issues.couchbase.com/browse/JSCBC-666[JSCBC-666]:
Fixed ConjunctionSearchQuery not being able to add queries.
* http://issues.couchbase.com/browse/JSCBC-665[JSCBC-665]:
Fixed search query not using the correct indexes.
* http://issues.couchbase.com/browse/JSCBC-677[JSCBC-677]:
Fixed search query consistency not being set in some cases.
* http://issues.couchbase.com/browse/JSCBC-668[JSCBC-668]:
Fixed an UnhandledPromiseRejection error which could occur.
* http://issues.couchbase.com/browse/JSCBC-673[JSCBC-673]:
Improved handling of cluster closing.
* http://issues.couchbase.com/browse/JSCBC-711[JSCBC-711]:
Fixed a case where closing connections could trigger a segfault.
* http://issues.couchbase.com/browse/JSCBC-695[JSCBC-695]:
Fixed issue with the use of custom connection string options.
* http://issues.couchbase.com/browse/JSCBC-683[JSCBC-683]:
Fixed inconsistent metrics data from query service.
* Updated to latest version of all dependencies.
* Adjusted prebuilt binaries to match currently support Node.js versions.

=== Known Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Buffer objects containing non-UTF8 data can become mangled when inserting them into a bucket or collection.  
This has been corrected in 3.0.4.


== Version 3.0.0 (20 January 2020)

This is the first GA release of the third generation Node.js SDK.

[source,console]
----
$ npm install couchbase@3.0.0
----

http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.0/[API Reference]

=== New Features

* Updated to libcouchbase 3.0.0

=== Fixed Issues

* http://issues.couchbase.com/browse/JSCBC-653[JSCBC-653]:
Fixed transcoding in getReplica and getAndTouch.
* http://issues.couchbase.com/browse/JSCBC-650[JSCBC-650]:
Improved stream wrappers to support both events and async/await.
* http://issues.couchbase.com/browse/JSCBC-657[JSCBC-657]:
Fixed some error double-translation issues.
* http://issues.couchbase.com/browse/JSCBC-652[JSCBC-652]:
Fixed issue with data structures exist checks.
* http://issues.couchbase.com/browse/JSCBC-655[JSCBC-655]:
Fixed search query constructors not being exported.
* http://issues.couchbase.com/browse/JSCBC-656[JSCBC-656]:
Renamed QueryProfile to QueryProfileMode.
* http://issues.couchbase.com/browse/JSCBC-639[JSCBC-639]:
Updated tests to reflect updated libcouchbase behaviour.
* http://issues.couchbase.com/browse/JSCBC-654[JSCBC-654]:
Updated to the latest mock to resolve test issue.
* http://issues.couchbase.com/browse/JSCBC-647[JSCBC-647]:
Marked all error contexts as uncommitted.
* http://issues.couchbase.com/browse/JSCBC-596[JSCBC-596]:
Marked defaultScope, scope, and collection methods uncommitted.

=== Known Issues

* http://issues.couchbase.com/browse/JSCBC-759[JSCBC-759]:
Buffer objects containing non-UTF8 data can become mangled when inserting them into a bucket or collection.  
This has been corrected in 3.0.4.


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 3.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
// end::all[]
