= Client Settings
:description: Client settings
:page-topic-type: reference
:page-aliases: ROOT:client-settings
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

TIP: The backend implementation of client settings changed substantially in 4.0.
Full details can be found in https://docs.couchbase.com/sdk-api/couchbase-node-client/interfaces/ConnectOptions.html[the API Reference].

// == Timeout Options

// section on wide area network support

== Commonly Used Options

The defaults above have been carefully considered and in general it is not recommended to make changes without expert guidance or careful testing of the change.
Some options may be commonly used together in certain envionments or to achieve certain effects.

=== Constrained Network Environments

Though xref:project-docs:compatibility.adoc#network-requirements[wide area network] (WAN) connections are not directly supported, some development and non-critical operations activities across a WAN are convenient.
Most likely for connecting to Couchbase Capella, or Server running in your own cloud account, whilst developing from a laptop or other machine not located in the same data center.
These settings are some you may want to consider adjusting:

* Connect Timeout to 30s
* Key-Value Timeout to 5s
* Config Poll Interval to 10s
* Circuit Breaker ErrorThresholdPercentage to 75

NOTE: As of SDK API 3.4 you can also use a *Configuration Profile*, which allows you to quickly configure your environment for common use-cases.
See the <<configuration-profiles>> section for more details.


== Configuration Profiles

Configuration Profiles provide predefined client settings that allow you to quickly configure an environment for common use-cases.
When using a configuration profile, the current client settings are overridden with the values provided in the profile.
Any property that is not specified in the profile is left unchanged.

CAUTION: The Configuration Profiles feature is currently a xref:nodejs-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.

=== WAN Development

*Cluster Method:* `applyProfile("wanDevelopment")`

A `wanDevelopment` configuration profile can be used to modify client settings for development or high-latency environments.
This profile changes the default timeouts.


// table - WAN profile timeouts
include::{version-common}@sdk:shared:partial$client-settings-wan-profile.adoc[tag=profile-values]
