= Document 
:nav-title: Documents & Doc Ops
:page-topic-type: concept
//:page-aliases: ROOT:core-operations
:page-aliases: ROOT:documents,ROOT:documents-basics,ROOT:documents-atomic

[abstract]
Couchbase supports CRUD operations, various data structures, and binary documents.

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based kv interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////





include::6.5@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,javascript]
----
upsert(docid, document)
insert(docid, document)
replace(docid, document)
get(docid)
remove(docid)
----

include::6.5@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::6.5@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[sub-document] operations which operate on specific subsets of documents:

[source,javascript]
----
await collection.mutateIn('customer123', [
    couchbase.MutateInSpec.upsert("fax", '311-555-0151')],
])
----

or xref:6.6@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,n1ql]
----
update `default` SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::6.5@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,n1ql]
----
SELECT * FROM default USE KEYS ["docid"];
----

or

[source,n1ql]
----
SELECT * FROM default WHERE META(default).id = "docid";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[sub-document operations], by specifying one or more sections of the document to be retrieved

[source,javascript]
----
var res = await collection.get('user:kingarthur', {
    project: ['contact.name', 'contact.email']
})

// res.content:
// {
//   'contact': {
//     'name': 'King Arthur',
//     'email': 'theking@knightsoftheroundtable.com',
//   }
// }
----

// Counters

include::6.5@sdk:shared:partial$documents.adoc[tag=counters1]

[source,python]
----
# Python example
>>> cb.counter('counter_id', delta=20, initial=100).value
100L
>>> cb.counter('counter_id', delta=1).value
101L
>>> cb.counter('counter_id', delta=-50).value
51L
----
include::6.5@sdk:shared:partial$documents.adoc[tag=counters2]

[source,python]
----
rv = cb.get('counter_id')
value, cas = rv.value, rv.cas
if should_increment_value(value):
  cb.upsert('counter_id', value + increment_amount, cas=cas)
----

include::6.5@sdk:shared:partial$documents.adoc[tag=counters3]

// Expiry
include::6.5@sdk:shared:partial$documents.adoc[tag=expiration]


////
include::6.5@sdk:shared:partial$documents.adoc[tag=]


include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]
////
