= Document
:description: Couchbase supports CRUD operations, various data structures, and binary documents.
:nav-title: Documents & Doc Ops
:page-topic-type: concept
//:page-aliases: ROOT:core-operations
:page-aliases: ROOT:documents,ROOT:documents-basics,ROOT:documents-atomic

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based kv interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////





include::{version-server}@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,javascript]
----
upsert(docid, document)
insert(docid, document)
replace(docid, document)
get(docid)
remove(docid)
----

include::{version-server}@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::{version-server}@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[sub-document] operations which operate on specific subsets of documents:

[source,javascript]
----
await collection.mutateIn('customer123', [
    couchbase.MutateInSpec.upsert("fax", '311-555-0151')],
])
----

or xref:{version-server}@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,n1ql]
----
update `travel-sample`.inventory.airline SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::{version-server}@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,n1ql]
----
SELECT * FROM `travel-sample`.inventory.airport USE KEYS ["airport_1254"];
----

or

[source,n1ql]
----
SELECT * FROM `travel-sample`.inventory.airport WHERE META().id = "airport_1254";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[sub-document operations], by specifying one or more sections of the document to be retrieved

[source,javascript]
----
var res = await collection.get('user:kingarthur', {
    project: ['contact.name', 'contact.email']
})

// res.content:
// {
//   'contact': {
//     'name': 'King Arthur',
//     'email': 'theking@knightsoftheroundtable.com',
//   }
// }
----

// Counters

include::{version-server}@sdk:shared:partial$documents.adoc[tag=counters1]

[source,javascript]
----
var counterDocId = "counter-doc";
// Increment by 1, creating doc if needed
const result = await collection.binary().increment(counterDocId, 1, {
    initial: 1000
});
// Decrement by 1
const result = await collection.binary().decrement(counterDocId, 1);
----

In the preceding example, a counter is created by using the `counter` method with an `initial` value.
The initial value is the value the counter uses if the counter document doesn't yet exist.

Once created, the counter can be incremented or decremented atomically by a given _amount_ or _delta_.
Specifying a positive delta increments the value and specifying a negative one decrements it.
When a counter operation is complete, the application receives the current value of the counter, after the increment.

Couchbase counters are limited to a 52-bit unsigned integer, Javascript's maximum safe integer.
Many SDKs limit the _delta_ argument to the value of a _signed_ 64-bit integer.

<<expiry,Expiration>> times can also be specified when using counter operations.

xref:howtos:concurrent-document-mutations.adoc[CAS] values aren't used with counter operations since counter operations are atomic.
The intent of the counter operation is to simply increment the current server-side value of the document.
If you want to only increment the document if it is at a certain value, then you may use a normal `get` function coupled with an increment:

[source,javascript]
----
const result = await collection.get(counterDocId);
value = result.value
if (shouldIncrementValue){
    const result = await collection.binary().increment(counterDocId, incrementValue);
}
----

include::{version-server}@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `collections.binary()`.
This enables you to work with counters using `get()` and `upsert()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters https://docs.couchbase.com/sdk-api/couchbase-node-client/BinaryCollection.html[in the API docs].

// Expiry
include::{version-server}@sdk:shared:partial$documents.adoc[tag=expiration]
