= Couchbase Node.js SDK 4.1
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Node.js SDK allows you to connect to a Couchbase Server cluster from Node.js.
The Node.js SDK is a native Node.js module that uses the very fast Couchbase++ library to handle communicating with the cluster over the Couchbase binary protocol.


[.column]
[.content]
[source,javascript]
----
const queryResult = await cluster.query("SELECT * FROM `travel-sample`.inventory.hotel WHERE city=$1 LIMIT 10", { parameters: ['Paris']});
queryResult.rows.forEach((row)=>{
   console.log(row);
});
----


++++
</div>
++++

[.column]
====== {empty}

== Couchbase Node.js SDK 4.1

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
Dive right in with a quick install and Hello World guide for xref:start-using-sdk.adoc[Node.js SDK].
// or xref:start-using-ottoman.adoc[Ottoman ODM]. 
Try out our xref:sample-application.adoc[Travel Sample Application].
And take a look at the xref:howtos:working-with-collections.adoc[Scopes and Collections].


[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)];
xref:howtos:n1ql-queries-with-sdk.adoc[Query];
xref:howtos:full-text-searching-with-sdk.adoc[Search];
xref:howtos:analytics-using-sdk.adoc[Analytics];
xref:howtos:view-queries-with-sdk.adoc[Views] --
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.
[]
https://docs.couchbase.com/sdk-api/couchbase-node-client[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
// Check out https://ottomanjs.com/#introduction[Ottoman ODM^], an Object Document Mapper library built for Node.js and Couchbase, for speedier, scalable development. 
Multi-Document xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[Distributed ACID Transactions] from the Node.js SDK.

Leverage the new Couchbase Server Scopes and Collection features to build multi-tenant micro-service application.


[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to
xref:project-docs:compatibility.adoc[compatibility tables];
xref:project-docs:sdk-release-notes.adoc[release notes];
xref:project-docs:get-involved.adoc[contribution guide]; and the
xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for moving to the 3.0 API.

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/node-js-sdk/12[Couchbase forums^].
The Node.js SDK can be combined with many other projects in the broader JavaScript ecosystem and beyond -- in the https://blog.couchbase.com/?s=Node.js[Couchbase Blog^] there are examples covering everything from Apache OpenWhisk to Vue.js.

++++
</div>
++++

