= Sample Application
:description: Discover how to program interactions with the Couchbase Server via the data, Query, and search services -- using the Travel Sample Application with the built-in Travel Sample data Bucket.
:nav-title: Travel Sample App
:content-type: tutorial
:page-topic-type: tutorial
:page-aliases: ROOT:sample-application,ROOT:tutorial4,ROOT:sample-app-backend

:travel-sample-git-project: try-cb-nodejs
:travel-sample-entrypoint: index.js

// TODO: move these to attributes.adoc
:name-sdk: Node.js SDK
:version-sdk: 3.0

[abstract]
{description}
This version demonstrates various features of Couchbase, including the Collections feature new in Server 7.0.


== Quick Start

Fetch the https://github.com/couchbaselabs/{travel-sample-git-project}[Couchbase {name-sdk} travel-sample Application REST Backend] from github:

[source,bash,subs="+attributes"]
----
git clone https://github.com/couchbaselabs/{travel-sample-git-project}.git
cd {travel-sample-git-project}
----

With https://docs.docker.com/get-docker/[Docker] installed, you should now be able to run a bare-bones copy of Couchbase Server, load the travel-sample, add indexes, install the sample-application and its frontend, all by running a single command:

[source,bash]
----
docker-compose up
----

== Running the code against your own development Couchbase server.

// TODO: extract these to shared
// tag::prereq[]
For Couchbase Server {version-server}, make sure that you have at least one node each of data; query; index; and search.
For a development box, mixing more than one of these on a single node (given enough memory resources) is perfectly acceptable.

If you have yet to install Couchbase Server in your development environment
xref:{version-server}@server:getting-started:do-a-quick-install.adoc[start here].

Then load up the Travel Sample Bucket, using either the
xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the
xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
You will also need to
xref:{version-server}@server:fts:fts-searching-from-the-ui.adoc#create-an-index[create a Search Index]
-- Query indexes are taken care of by the Sample Bucket.
// end::prereq[]

See the README at https://github.com/couchbaselabs/{travel-sample-git-project} for full details of how to run and tweak the {name-sdk} travel-sample app.


== Using the Sample App

// TODO: *PIC -- screenshot

Give yourself a username and password and click *Register*.

Now try out a few queries, and see Search in action for the hotel finder feature.


== Sample App Backend

The backend code shows Couchbase {name-sdk} in action with Query and Search,
but also how to plug together all of the elements and build an application with Couchbase Server and the {name-sdk}.

Here's the airport search code, which checks to see whether the search term for the query string is a three or four letter FAA or ICAO abbreviation, and if not searches for it as an airport name:

// TODO: discuss if we need source code example, and how we'll keep it up to date.
[source,javascript]
----
var qs;
  if (searchTerm.length === 3) {
    // FAA code
    qs = `SELECT airportname from \`travel-sample\` WHERE faa = '${searchTerm.toUpperCase()}';`;
  } else if (searchTerm.length === 4 &&
      (searchTerm.toUpperCase() === searchTerm ||
        searchTerm.toLowerCase() === searchTerm)) {
    // ICAO code
    qs = `SELECT airportname from \`travel-sample\` WHERE icao = '${searchTerm.toUpperCase()}';`;
  } else {
    // Airport name
    qs = `SELECT airportname from \`travel-sample\` WHERE LOWER(airportname) LIKE '%${searchTerm.toLowerCase()}%';`;
  }

  let result, rows;
  try {
    result = await cluster.query(qs);
    rows = result.rows;
  } catch (error) {
    console.error(error)
  };

  res.send({
    data: rows,
    context: [qs]
  });
----

The https://github.com/couchbaselabs/{travel-sample-git-project}/blob/HEAD/{travel-sample-entrypoint}[{travel-sample-entrypoint}] file also contains the functions for handling users, registration, and N1QL queries.


== Data Model

// TODO, update the Data Model page!
See the xref:ref:travel-app-data-model.adoc[Travel App Data Model] reference page for more information about the sample data set used.

== REST API

You can explore the REST API here in read-only mode, or once you are running the application, at the `/apidocs` endpoint.

swagger_ui::https://raw.githubusercontent.com/couchbaselabs/{travel-sample-git-project}/HEAD/swagger.json[]
