= Install and Start Using the Node.js SDK with Couchbase Server
:navtitle: Start Using the SDK

[abstract]
The Couchbase Node.js SDK enables you to interact with a Couchbase Server cluster from the Node.js language.

WARNING: These pages cover the first _Developer Preview_ of the Couchbase Node.js SDK 3.0 (DP1).
As such they are likely to change without notice.
The DP1 code _should not_ be used in production.

== Installing the SDK

[source,javascript]
----
npm install couchbase
----

Information on new features, fixes, known issues, as well as information on how to install older release versions is xref::project-docs:relnotes-nodejs-sdk.adoc[in the release notes].

== Hello Couchbase

Now you have the Node.js client installed, try out the following:

[source,javascript]
----
var cluster = new couchbase.Cluster(
    'http://10.112.180.101:8091', {
        username: 'Administrator',
        password: 'password'});
----

Couchbase uses xref:6.5@server:learn/security:roles.adoc[Role Based Access Control (RBAC) to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:3.0dp1@net-sdk:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.

[source,javascript]
----
// get a bucket reference
var bucket = cluster.bucket('bucket-name');
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,javascript]
----
// get a collection reference
var collection = bucket.defaultCollection();
var myCollection = bucket.collection("my-collection");
----

The 3.0 SDK is ready for the introduction of xref:#[Collections] in an upcoming release of the Couchbase Data Platform.
The latest release, Mad Hatter, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to a specified _Collection_.
Here we will use the `DefaultCollection`, rather than a specific collection, but best practice would be to group your users into a single collection, groups into another, etc...

[source,javascript]
----
// upsert document
var upsertResult = await collection.upsert("my-document", {name: 'mike'});

// get document
var getResult = await collection.get("my-document");
----

KV Operations are described in detail on the xref:net-sdk:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page -- or first see a complete worked example of using the Couchbase .NET client, our xref:3.0dp1@sample-application.adoc[Travel Sample Application].

== Additional Resources

The API reference is generated for each release and can be found xref:http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.0dp1/[here].

xref:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Node.js SDK.
The Node.js SDK source code is available on xref:https://github.com/couchbase/couchbase-node-client[GitHub].


