= Install and Start Using the Node.js SDK with Couchbase Server
:description: The Couchbase Node.js SDK enables you to interact with a Couchbase Server or Capella cluster from the Node.js runtime, using TypeScript or JavaScript.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK
:page-toclevels: 2


[abstract]
{description}

The Couchbase SDK API 3 (implemented by Node.js SDK 3._x_ and 4._x_) is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for Couchbase Server features like xref:concept-docs:collections.adoc[Collections and Scopes] (available from Couchbase Server 7.0).

Node.js SDK 4._x_ implements the same SDK API 3 bindings, but the internals are completely rewritten -- 
using the Couchbase++ library rather than libcouchbase -- to allow upcoming new features such as transactions, and fix some long-standing bugs. 
Please note any xref:project-docs:migrating-sdk-code-to-3.n.adoc#sdk4-specifics[caveats] in the migration guide.


== Hello Couchbase

On this page we show you how to quickly get up and running -- installing the Couchbase Node.js SDK, and trying out the Hello World code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella (JavaScript)::
+
--
To connect to xref:cloud::index.adoc[Couchbase Capella], be sure to get the correct endpoint as well as user, password and bucket name.

[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tags=**]
----
--

Couchbase Capella (TypeScript)::
+ 
-- 
To connect to xref:cloud::index.adoc[Couchbase Capella], be sure to get the correct endpoint as well as user, password and bucket name.

[source,typescript]
----
include::example$cloud.ts[tags=**]
----
--

Local Couchbase Server::
+ 
--
As well as the Node.js SDK, and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:7.1@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:7.1@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].

[source,nodejs]
----
include::example$start-using.js[tags=**]
----
--
====

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.

== Quick Installation

[source,console]
----
$ npm install couchbase --save
----

This will download the latest Couchbase Node.js SDK, and add a dependency to your `package.json`.

Information on new features, fixes, known issues, as well as information on how to install older release versions is in the xref:project-docs:sdk-release-notes.adoc[release notes], and a fuller installation guide can be found xref:project-docs:sdk-full-installation.adoc[here].

=== TypeScript Support

If you intend to use `TypeScript` instead of `JavaScript`, then also do the following:

[source,console]
----
$ npm install -g typescript ts-node
----

== Step by Step

Create an empty file named `index.js`, or alternatively `index.ts` for TypeScript, and walk through step by step:

* Connect to a single node cluster, bucket, and collection
* Add and retrieve a new document
* Look up (SQL-type query) the new document by attribute value

=== Prerequisites

Here are all of the imports that you will need to run the sample code.

[{tabs}]
====
JavaScript::
+ 
-- 
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=imports,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript]
----
include::example$cloud.ts[tag=ts-imports,indent=0]
----
--
====

Now, create an empty `main()` function.

[source,javascript,indent=0]
----
async function main() {
  // add code here...
}
----

We will update this function as we go along the steps in this guide.

=== Connection

[{tabs}]
====
Couchbase Capella (JavaScript)::
+ 
-- 
IMPORTANT: Couchbase Capella requires mandatory use of TLS (Transport Layer Security).
As of Node.js SDK version 4.1, the standard certificate required to connect to a Capella cluster is automatically included with no additional configuration.

[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=connect,indent=0]
----

Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to database resources.
For the purposes of this example, we can use the _Organization Owner_ role automatically assigned to a user account during installation of the Capella cluster.
This role grants full access to a Capella organization, including full data access to all projects and clusters.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice. 

For the SDK client to access cluster data, you will need to set up credentials for your database by xref:cloud:get-started:cluster-and-data.adoc#credentials[following these steps].
--

Couchbase Capella (TypeScript)::
+ 
--
IMPORTANT: Couchbase Capella requires mandatory use of TLS (Transport Layer Security).
As of Node.js SDK version 4.1, the standard certificate required to connect to a Capella cluster is automatically included with no additional configuration.

[source,typescript,indent=0]
----
include::example$cloud.ts[tag=ts-connect]
----

Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to database resources.
For the purposes of this example, we can use the _Organization Owner_ role automatically assigned to a user account during installation of the Capella cluster.
This role grants full access to a Capella organization, including full data access to all projects and clusters.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice. 

For the SDK client to access cluster data, you will need to set up credentials for your database by xref:cloud:get-started:cluster-and-data.adoc#credentials[following these steps].
--

Local Couchbase Server::
+ 
--
[source,javascript]
----
include::example$start-using.js[tag=connect,indent=0]
----

Couchbase uses xref:7.1@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
For the purposes of this example, we are connecting to Couchbase using the _Full Admin_ role created during the installation of our Couchbase Server.

Since we are running this locally, we are using the Couchbase alias for localhost.
--
====

Following successful authentication, the bucket can be opened:

[{tabs}]
====
JavaScript::
+ 
--
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=bucket,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript]
----
include::example$cloud.ts[tag=ts-bucket,indent=0]
----
--
====

NOTE: We are working with the xref:7.1@server:manage:manage-settings/install-sample-buckets.adoc[travel-sample] data bucket. 
If you are not, update the `bucketName` variable used in the example with your own.

The Node.js SDK supports full integration with the xref:concept-docs:collections.adoc[Collections] feature introduced in Couchbase Server 7.0.
_Collections_ allow documents to be grouped by purpose or theme, according to a specified _Scope_.
Here we will use the `users` collection within the `tenant_agent_00` scope from `travel-sample` bucket as an example.

[{tabs}]
====
JavaScript::
+ 
--
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=collection,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript]
----
include::example$cloud.ts[tag=ts-collection,indent=0]
----
--
====

The code shows how you would use a named collection and scope. 
A named or default collection will provide the same functionality as bucket-level operations did in previous versions of Couchbase Server.

The `defaultCollection` must be used when connecting to a 6.6 cluster or earlier.

[{tabs}]
====
JavaScript::
+ 
--
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=default-collection,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript]
----
include::example$cloud.ts[tag=ts-default-collection,indent=0]
----
--
====

=== Document Addition and Retrieval 

Let's create a document in our application that we can add to our `travel-sample` bucket that conforms to the structure of a document of type `user`.

[{tabs}]
====
JavaScript::
+ 
--
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=test-doc,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript]
----
include::example$cloud.ts[tag=ts-test-doc,indent=0]
----
--
====

xref:howtos:kv-operations.adoc[Document operations], such as storing and retrieving documents, can be done using `Collection.Upsert()` and `Collection.Get()`.
Simply pass the key (and value, if applicable) to the relevant methods.

The following code will _upsert_ a document into the database:

[{tabs}]
====
JavaScript::
+ 
--
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=upsert,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript]
----
include::example$cloud.ts[tag=ts-upsert,indent=0]
----
--
====

Now, let's retrieve that document using a key-value operation. 
The following runs a _get_ for a document key and logs out the result in our console:

[{tabs}]
====
JavaScript::
+ 
--
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=get,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript]
----
include::example$cloud.ts[tag=ts-get,indent=0]
----
--
====

=== {sqlpp} Lookup

Couchbase {sqlpp} (formerly N1QL) queries are performed by invoking `Cluster.Query()`.

In the code below we will query Couchbase to retrieve airlines by country and print the results.

[{tabs}]
====
JavaScript::
+ 
--
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=query,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript,indent=0]
----
include::example$cloud.ts[tag=ts-query,indent=0]
----
--
====

=== Execute!

To ensure that we can run the main function, we add this last line of code:

[{tabs}]
====
JavaScript::
+ 
--
[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tag=run-main,indent=0]
----
--

TypeScript::
+ 
--
[source,typescript]
----
include::example$cloud.ts[tag=ts-run-main,indent=0]
----
--
====

Now we can run our code: 

[{tabs}]
====
JavaScript::
+ 
--
[source,console]
----
$ node index.js
----
--

TypeScript::
+ 
--
[source,console]
----
$ ts-node index.ts
----
--
====

The results you should expect are as follows:

[source,console]
----
got:  GetResult {
  content: {
    type: 'user',
    name: 'Michael',
    email: 'michael123@test.com',
    interests: [ 'Swimming', 'Rowing' ]
  },
  cas: Cas<1651756567733665792>,
  expiryTime: undefined
}
query row:  { name: 'Michael' }
----

== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our {sqlpp} language;
// * Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
// * A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The API reference is generated for each release and the latest can be found https://docs.couchbase.com/sdk-api/couchbase-node-client/index.html[here].

Links to each release are to be found in the xref:project-docs:sdk-release-notes.adoc[individual release notes].

The xref:project-docs:migrating-sdk-code-to-3.n.adoc[Migrating from SDK API 2 to 3] page highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Node.js SDK.
The Node.js SDK source code is available on https://github.com/couchbase/couchnode[GitHub].

// https://ottomanjs.com/[Ottoman] is an ODM built for Couchbase and Node.js.
// Ottoman's goal is to provide a better development experience while using Couchbase, bringing to developers a reliable tool to build systems that are easy to design, maintain, and scale.

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/node-js-sdk/12[community forum] is a great source of help.
