= Install and Start Using the Node.js SDK with Couchbase Server
:description: Installing the Couchbase Node.js SDK & a Hello World program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK

[abstract]
The Couchbase Node.js SDK enables you to interact with a Couchbase Server cluster from the link:https://nodejs.org/[Node.js language].

The Couchbase Node.js SDK 3._x_ is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for Couchbase Server features like xref:concept-docs:collections.adoc[Collections and Scopes] (available from Couchbase Server 7.0).

The 3.x SDK also brings in link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises[promises], to reduce the complexity of asynchronous javascript in client applications, as well as extending the management APIs and bringing better debugging and logging options

// tag::prep[]

// end::prep[]

// tag::install[]

== Creating a New Node.js Project
// This section is optional

Creating a Node.js project is as easy as making a directory and initializing it with npm. The next two commands will do that for us. Open up a terminal and run the following command:

[source,console]
----
$ mkdir node-couchbase-project && cd $_
----

The command above will make our directory and change our current working directory.

[source,console]
----
$ npm init -y
----

If a directory does not already have a `package.json` at its root, this means it is not initialized. The command above will accomplish this.

Note: We have used the `-y` flag to take the initialization defaults. To change any of these defaults, just open the `package.json` and manually make any changes.

[source,json,indent=0]
----
include::../examples/example-package.json[]
----

== Installing the SDK

The Couchbase Node.js Client will run on any https://nodejs.org/en/download/[supported LTS version of Node.js].

[source,console]
----
$ npm install couchbase --save
----

Note: This will download the latest Couchbase Node.js SDK, and add a dependency to your `package.json`.

// end::install[]

Information on new features, fixes, known issues, as well as information on how to install older release versions is in the xref:project-docs:sdk-release-notes.adoc[release notes].

=== TypeScript Support

NOTE: Follow this section only if you intend to use `TypeScript` instead of `JavaScript`.

Since release 3.2, the Node.js SDK has added full support for the link:https://www.typescriptlang.org/[TypeScript] programming language. 

[source,console]
----
$ npm install -g typescript ts-node
----

This will install TypeScript globally on your machine and allow you to run commands with the `tsc` cli. You will have noticed that we also install link:https://typestrong.org/ts-node/[ts-node] which is a handy execution utility that will help us run the example later on.

Before we can get started, run `tsc --init` in the `node-couchbase-project` directory
to generate a `tsconfig.json` file. This will set you up with some initial configurations, which should suffice for our purposes. 

Should you wish to make changes in future you can simply edit the file:

[source,json,indent=0]
----
include::../examples/example-tsconfig.json[]
----

Note that the example above does not include the generated comments for readability.


== Hello Couchbase

At this point we want to transition from the terminal to your code editor of choice and point to the directory we have just created named `node-couchbase-project`.

Let's now create an empty file named `index.js`, or alternatively `index.ts` for TypeScript, and walk through step by step adding code to enable us to connect to a bucket, add a document and retrieve it using a key-value get operation:

[{tabs}]
====
JS::
+ 
-- 
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=connect]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-connect]
----
--
====

If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella] rather than a local Couchbase Server, see the <<cloud-connections, Cloud section>>, below.

Couchbase uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
For the sake of this example, we are connecting to Couchbase using the _Full Admin_ role created during the installation of our Couchbase Server.
Since we are running this locally, we are using the Couchbase alias for localhost.

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=bucket]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-bucket]
----
--
====

If you are not working with the `travel-sample` data bucket, substitute _travel-sample_ with your _bucket-name_.

The 3.2 SDK is ready for the introduction of xref:concept-docs:collections.adoc[Collections] in the xref:{version-server}@server:introduction:whats-new.adoc#whats-new-server-700[7.0 release] of the Couchbase Data Platform.
The latest release, Couchbase Server 7.0, brings Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=collection]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-collection]
----
--
====

NOTE: This feature was previously available as a _developer preview_ from Couchbase Server 6.6. _When connecting to a 6.6 cluster or earlier_, we must use the `DefaultCollection`, which covers the whole Bucket.

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=default-collection]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-default-collection]
----
--
====

Let's create a document in our application that we can add to our `travel-sample` bucket that conforms to the structure of a document of type `airline`.

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=test-doc]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-test-doc]
----
--
====

Now we will create a function that will take care of upserting that document. This function is of type `async` and simply awaits the result of the upsert and either logs out the result or error in our console:

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=upsert-func]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-upsert-func]
----
--
====

Now, we can simply call the `upsertDocument` function passing in our `airline` document:

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=upsert-invoke]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-upsert-invoke]
----
--
====

We can turn around and retrieve that document using a key-value operation. Let's create a function that takes a document key that is of type `async` and awaits the result of the get operation and either logs out the result or error in our console:

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=get-func]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-get-func]
----
--
====

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].

Now, we can simply call the `getAirlineByKey` function passing in our valid document key `airline_8091` and close our `main` function:

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=get-invoke]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-get-invoke]
----
--
====

To ensure that we can run the main function, we add this last line of code:

[{tabs}]
====
JS::
+ 
--
[source,javascript,indent=0]
----
include::../examples/start-using.js[tag=run-main]
----
--

TS::
+ 
--
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tag=ts-run-main]
----
--
====

Now we can run our code: 

[{tabs}]
====
JS::
+ 
--
[source,console]
----
$ node index.js
----
--

TS::
+ 
--
[source,console]
----
$ ts-node index.ts
----
--
====

The results you should expect are as follows:

[source,bash]
----
Upsert Result: 
MutationResult {
  cas: CbCas { '0': <Buffer 00 00 3e b7 72 65 a0 16> },
  token: CbMutationToken {
    '0': <Buffer bf 02 e0 23 a7 4d 00 00 58 00 00 00 00 00 00 00 a9 03 00 00 00 00 00 00 74 72 61 76 65 6c 2d 73 61 6d 70 6c 65 00 00 00 48 54 83 05 01 00 00 00 30 54 ... 230 more bytes>
  }
}
Get Result: 
GetResult {
  content: {
    type: 'airline',
    id: 8091,
    callsign: 'CBS',
    iata: null,
    icao: null,
    name: 'Couchbase Airways'
  },
  cas: CbCas { '0': <Buffer 00 00 3e b7 72 65 a0 16> },
  expiryTime: undefined
}
----


== Full Example

If you want to copy and paste to run the full example, here it is:

[{tabs}] 
==== 
JS::
+ 
-- 
[source.try-it,nodejs,indent=0]
----
include::../examples/start-using.js[tags=**]
----
--

TS::
+ 
-- 
[source,typescript,indent=0]
----
include::../examples/start-using.ts[tags=**]
----
--

Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as user, password, and `couchbasecloudbucket`  -- and see the <<cloud-connections, Cloud section>>, below.

[source,javascript]
----
include::devguide:example$nodejs/cloud.js[tags=**]
----
--
====


== Cloud Connections

If you are not working from the same _Availability Zone_ as your Capella instance, refer to the following:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments],
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements],
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].



== Additional Resources

The API reference is generated for each release and the latest can be found https://docs.couchbase.com/sdk-api/couchbase-node-client/modules.html[here].

Links to each release are to be found in the xref:project-docs:sdk-release-notes.adoc[individual release notes].

The xref:project-docs:migrating-sdk-code-to-3.n.adoc[Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Node.js SDK.
The Node.js SDK source code is available on https://github.com/couchbase/couchnode[GitHub].

https://ottomanjs.com/[Ottoman] is an ODM built for Couchbase and Node.js.
Ottoman's goal is to provide a better development experience while using Couchbase, bringing to developers a reliable tool to build systems that are easy to design, maintain, and scale.
