= The Ottoman ODM with Couchbase Server
:description: Installing the Ottoman ODM & a Hello World program.
:navtitle: Start using the Ottoman ODM

include::project-docs:partial$attributes.adoc[]


[abstract]
{description}

Ottoman is an open-source Object Document Mapper(ODM) library, built for Node.js and Couchbase, that aspires to give developers an even better experience when building modern applications.

Ottoman ODM adds an abstraction layer over Couchbase Node.js SDK and significantly reduces the level of boilerplate needed during application development. 
It provides features such as the ability to define document schemas and perform validations on your data in a NoSQL landscape -- 
which is inherently schema-less or schema-flexible by nature. 

NOTE: Whether you are building your application with JavaScript or TypeScript, Ottoman will work seamlessly with either.

Ottoman fully supports the xref:{version-server}@server:learn:data/scopes-and-collections.adoc[Scopes and Collections] features introduced in Couchbase Sever 7.0. 
We recomend familiarizing yourself with these concepts before proceeding with this guide.

For a full feature comparison between Ottoman ODM and the Couchbase Node.js SDK you can read more https://ottomanjs.com/guides/sdk-comparison.html#ottoman-vs-sdk-comparison[here^].


== Support in Node.js SDK 4.0

Ottoman is currently *not supported* in Node.js SDK 4.0.
We intend to fully support it with the next 4.1 release.

In the meantime, if you are interested in checking out Ottoman, please
read the xref:3.2@nodejs-sdk:hello-world:start-using-ottoman.adoc[Ottoman for Node.js SDK 3.2] page, or explore the resources below.

== Additional Resources

To learn more about Ottoman ODM you can head over to the official https://ottomanjs.com/[Ottoman^] page.
You can also find more in-depth information on some of the topics we touched on:

* https://ottomanjs.com/guides/schema.html[Schemas^]
* https://ottomanjs.com/guides/model.html[Models^]
* https://ottomanjs.com/guides/document.html[Documents^]
* https://ottomanjs.com/guides/query-builder.html[Query Builder^]

If you are evaluating whether to use Ottoman in your next project, the FAQs https://ottomanjs.com/guides/faq.html[here] should also answer some questions.

Links to each release are to be found in the xref:project-docs:ottoman-release-notes.adoc[individual release notes].

Couchbase welcomes community contributions to the Ottoman ODM.
The Ottoman ODM source code is available on https://github.com/couchbaselabs/node-ottoman[GitHub^].
