= Start Using the Ottoman ODM
:description: Installing the Ottoman ODM & a Hello World program.
:page-pagination: full
:page-topic-type: tutorial

include::project-docs:partial$attributes.adoc[]


[abstract]
{description}

Ottoman is an open-source Object Document Mapper(ODM) library, built for Node.js and Couchbase, that aspires to give developers an even better experience when building modern applications.

Ottoman ODM adds an abstraction layer over Couchbase Node.js SDK and significantly reduces the level of boilerplate needed during application development. 
It provides features such as the ability to define document schemas and perform validations on your data in a NoSQL landscape -- 
which is inherently schema-less or schema-flexible by nature. 

NOTE: Whether you are building your application with JavaScript or TypeScript, Ottoman will work seamlessly with either.

Ottoman fully supports the xref:{version-server}@server:learn:data/scopes-and-collections.adoc[Scopes and Collections] features introduced in Couchbase Sever 7.0. 
We recomend familiarizing yourself with these concepts before proceeding with this guide.

For a full feature comparison between Ottoman ODM and the Couchbase Node.js SDK you can read more https://ottomanjs.com/docs/advanced/sdk-comparison[here^].


== Node.js SDK 4.x Support

https://ottomanjs.com/#introduction[Ottoman.js] version 2.3.0 and above are compatible with Couchbase Node.js SDK 4.2.0 and above.
Earlier versions of Ottoman ODM 2.x are only compatible with the 3.2 Node.js SDK.


== Additional Resources

To learn more about Ottoman ODM you can head over to the official https://ottomanjs.com/[Ottoman^] page.
You can also find more in-depth information on some of the topics we touched on:

* https://ottomanjs.com/guides/schema.html[Schemas^]
* https://ottomanjs.com/guides/model.html[Models^]
* https://ottomanjs.com/guides/document.html[Documents^]
* https://ottomanjs.com/guides/query-builder.html[Query Builder^]

If you are evaluating whether to use Ottoman in your next project, the FAQs https://ottomanjs.com/guides/faq.html[here] should also answer some questions.

Links to each release are to be found in the xref:project-docs:ottoman-release-notes.adoc[individual release notes].

Couchbase welcomes community contributions to the Ottoman ODM.
The Ottoman ODM source code is available on https://github.com/couchbaselabs/node-ottoman[GitHub^].

////
Future work - travel sample app
https://github.com/couchbaselabs/try-ottoman-ts 
https://github.com/couchbaselabs/try-ottoman
////
