= Hello World
:page-aliases: ROOT:getting-started.adoc,ROOT:start-using.adoc,ROOT:hello-couchbase.adoc,ROOT:start-using-sdk.adoc
:page-toclevels: 3
:description: Install, connect, try. A quick start guide to get you up and running with Couchbase and the {name-sdk}.
:forum-link: https://www.couchbase.com/forums/c/node-js-sdk/12
:page-partial:

// Note to editors
//
// This page pulls in content from
// https://github.com/couchbase/docs-sdk-common/blob/release/7.6/modules/shared/partials/start-using-sdk.adoc
//
// and code samples from
// https://github.com/couchbase/docs-sdk-nodejs/tree/temp/4.4/modules/devguide/examples/nodejs
//
// It can be seen built at
// https://docs.couchbase.com/nodejs-sdk/current/hello-world/start-using-sdk.html


[abstract]
{description}

Couchbase has a simple interface for creating and modifying records in a document,
based upon the *collection* into which the documents are organized.
You can read more about data modeling <<data-modeling,below>>,
but first let's look at those data operations, and installing the {name-sdk}.


.Upsert with a Unique ID
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=upsert,indent=0]
----

`upsert` inserts (creates) the document if it does not exist, or replaces it if it does.
We'll explore creating and retrieving data records in more detail <<create-read-update-delete,below>>,
after walking through a quick installation.


== Before You Start

Couchbase Capella, our Database-as-a-Service, lets you get on with what matters, while we take care of the administration for you.
Alternately, if you need to control every aspect of deployment --
or just want to run the Server in a VM on your laptop --
there are several self-managed options available:

[tabs]
====
Couchbase Capella::
+
--
If you haven't already got a cluster set up, the easiest route is to https://cloud.couchbase.com/sign-up[sign up to Couchbase Capella and deploy a free tier cluster^],
then come back to this page.
Make a note of the xref:cloud:get-started:connect.adoc[endpoint] to connect to,
and remember the credentials for the user that you set up.
--

Self-Managed Couchbase Server::
+
--
Install Couchbase Server locally, or in your private Cloud:

* xref:{version-server}@server:install:get-started.adoc[Deployment overview]
* xref:{version-server}@server:install:getting-started-docker.adoc[Docker Install]
* xref:operator::overview.adoc[Couchbase Autonomous Operator]
** xref:operator::install-kubernetes.adoc[Kubernetes]
** xref:operator::install-openshift.adoc[Openshift]
* xref:{version-server}server:cloud:couchbase-cloud-deployment.adoc[Cloud Marketplace]:
** xref:{version-server}@server:cloud:couchbase-aws-marketplace.adoc[AWS Marketplace]
** xref:{version-server}@server:cloud:couchbase-azure-marketplace.adoc[Azure Marketplace]
** xref:{version-server}@server:cloud:couchbase-gcp-cloud-launcher.adoc[GCP Marketplace]

For the example code below to run, you'll need the username and password of the Administrator user that you create, and the IP address of at least one of the nodes of the cluster.
--
====

// Script the docs!
// Can any of the SDK installations be scripted?

=== Prerequisites

* The Node.js SDK is tested against LTS versions of Node.js --
see the xref:project-docs:compatibility.adoc[compatibility docs].

The code examples also assume:

[tabs]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically when deploying a Capella free tier cluster.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to cluster resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In production, Couchbase strongly recommends setting up users with more granular access roles as a best practice for data security.
--

Self-Managed Couchbase Server::
+
--
* xref:{version-server}@server:getting-started/do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role-Based Access Control (RBAC)] to control access to cluster resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
In production, Couchbase strongly recommends setting up users with more granular access roles as a best practice for data security.
--
====

== Installation

More details of the installation process are in the
xref:project-docs:sdk-full-installation.adoc[full installation guide].

[source,console]
----
$ npm install couchbase --save
----

This will download the latest Couchbase Node.js SDK, and add a dependency to your `package.json`.

=== TypeScript Support

If you intend to use `TypeScript` instead of `JavaScript`, then also do the following:

[source,console]
----
$ npm install -g typescript ts-node
----

=== IDE Plugins

To make development easier, Couchbase plugins are available for VSCode and the IntelliJ family of IDEs and editors.
For links and more information about these and other integrations across the {name_platform} ecosystem,
check out the xref:project-docs:third-party-integrations.adoc[] page.

=== Grab the Code

If you're all set up and in a real hurry, just grab this code sample and add in your Capella details.

.Complete Hello World code sample [*Click to open or collapse the listing*]
[%collapsible]
=====
[tabs]
====
JavaScript::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[]
----
--

TypeScript::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[]
----
--
====
=====

Otherwise, read on as we introduce the CRUD API and connection to Capella or self-managed Couchbase Server.

TIP: There's a *View* link to the complete sample code on GitHub above each of the snippets on these SDK pages, and a *Copy* icon to grab just the snippet shown.

NOTE: The code samples on this page use ESModules, but the Node.js SDK is fully compatible with CommonJS as well. Specify the import syntax as needed.

== Connect to your Database

Connect to your Couchbase Capella operational cluster (or your local Couchbase Cluster, if you're trying out self-managed Couchbase).

[tabs]
====
Couchbase Capella (JavaScript)::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=connect,indent=0]
----

NOTE: SDK installation includes the client certificate for connecting to a Capella cluster.
--

Couchbase Capella (Typescript)::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[tag=connect,indent=0]
----

NOTE: SDK installation includes the client certificate for connecting to a Capella cluster.
--

Self-Managed Couchbase Server (Javascript)::
+
--
[source,javascript]
----
include::devguide:example$nodejs/self-managed-connection-crud.js[tag=connect,indent=0]
----
--

Self-Managed Couchbase Server (Typescript)::
+
--
[source,javascript]
----
include::devguide:example$nodejs/self-managed-connection-crud.ts[tag=connect,indent=0]
----
--
====


The xref:ref:client-settings.adoc[Client Settings] page covers `ClientOptions` in detail. 

For a deeper look at connection options, read xref:howtos:managing-connections.adoc[].

TIP: The connection code for getting started uses the Administrator password and credentials provided during set up.
In any production app, create a role restricted to the permissions needed for your app
// --
// more on this in xref:concept-docs:best-practices.adoc#roles-and-rbac[the Security documentation].

=== Opening a Bucket

Following successful authentication, open the bucket with:
[tabs]
====

Javascript::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=bucket,indent=0]
----
--

Typescript::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[tag=bucket,indent=0]
----
--

====

*Collections* allow documents to be grouped by purpose or theme, according to a specified *scope*. For more information, see data modeling, <<data-modeling,below>>.
The example here shows the `airport` collection, within the `inventory` scope, from the `travel-sample` bucket.

[tabs]
====

Javascript::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=collection,indent=0]
----
--

Typescript::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[tag=collection,indent=0]
----
--

====

== Create, Read, Update, Delete

Couchbase documents are organized into buckets, scopes, and collections.
https://en.wikipedia.org/wiki/CRUD[CRUD operations^] -- Create, Read, Update, Delete actions can be performed upon documents in a collection.

=== JSON

Create a regular javascript object to start with:

[tabs]
====

Javascript::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=json,indent=0]
----
--

Typescript::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[tag=json,indent=0]
----
--

====

=== Insert (Create) and Upsert

`insert` and `upsert` both create a new document.
The difference is, if a document with a key exists already, the `insert` operation fails 
// throwing `DocumentExistsException` --
and the `upsert` operation replaces the content and succeeds.

Provide a unique ID as the key, and use a UUID here:

.Creating a new document
[tabs]
====

Javascript::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=upsert,indent=0]
----
--

Typescript::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[tag=upsert,indent=0]
----
--

====

=== Get (Read)

The `get` method reads a document from a collection. 
The `get` method also throws `DocumentNotFoundError`, if the collection does not have a document with this ID.

[tabs]
====

Javascript::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=get,indent=0]
----
--

Typescript::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[tag=get,indent=0]
----
--

====

=== Replace (Update)

.The replace method updates the value of an existing document
[tabs]
====

Javascript::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=replace,indent=0]
----
--

Typescript::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[tag=replace,indent=0]
----
--

====

CAUTION: Always practice to use xref:howtos:concurrent-document-mutations.adoc[optimistic locking] when you replace a document. 
Else, changes might get lost if 2 people change the same document at the same time.

=== Remove (Delete)

The remove method deletes a document from a collection:

[tabs]
====

Javascript::
+
--
[source,javascript]
----
include::devguide:example$nodejs/capella_connection_crud.js[tag=remove,indent=0]
----
--

Typescript::
+
--
[source,typescript]
----
include::devguide:example$nodejs/capella_connection_crud.ts[tag=remove,indent=0]
----
--

====


== Data Modeling

Documents that belong together are organized into collections.
You decide what it means to "belong."
Developers group documents of the same type in a collection.

For example, there are two types of documents: customers and invoices.
You can organize the customer documents in a collection named `customers` and the invoice documents in a collection named `invoices`.

Every document belongs to a collection.
A document's ID is unique `within` the collection.

Different scopes can hold collections with different names.
There's no relationship between collections in different scopes.
Each collection belongs to 1 scope and a collection's name is unique within the scope.


You can find more details on the xref:concept-docs:data-model.adoc[Data Model page].
// The xref:student-record-developer-tutorial.adoc[Student Records Tutorial] gives an introduction to data modeling in a document database alongside using the {name-sdk}.


== What Next?

////
Query and KV -
both
- but different emphasis on modelling objects....
////



=== Help and Troubleshooting

* xref:howtos:troubleshooting-cloud-connections.adoc[Troubleshooting common network problems].
* {forum-link}[Help forum].
* https://discord.com/channels/915294689681362954/1217642561645318194[Discord channel].
* Read the xref:howtos:error-handling.adoc[error handling page].
* xref:cloud:get-started:capella-iq/get-started-with-iq.adoc#generate-sdk-code-preview[Get help from Couchbase iQ].

// === Next Steps

// * Take a look at the xref:hello-world:sample-application.adoc[].
// * xref:concept-docs:data-durability-acid-transactions.adoc[Learn more about the Data Service].
// * xref:concept-docs:querying-your-data.adoc[Discover SQL++] -- our SQL-family querying language.
// * Explore some of the xref:project-docs:third-party-integrations.adoc[third party integrations] with Couchbase and the {name_platform} SDK, across the {name_platform} ecosystem.


////
== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know.
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] (CRUD) against a document database.
* Or xref:howtos:sqlpp-queries-with-sdk.adoc[Query] with our SQL-based {sqlpp} query language.
* Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service].
* A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search].
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The Scala SDK includes three APIs.
The examples above show the simple blocking API. 
You can also perform all the operations in an async style using Scala `Future` and a reactive style using Project Reactor `SMono` and `SFlux`.
For more information, see xref:howtos:concurrent-async-apis.adoc[Choosing an API].

The API reference is generated for each release and the latest can be found https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/index.html[here].

Couchbase welcomes community contributions to the Scala SDK.
The SDK source code is available on https://github.com/couchbase/couchbase-jvm-clients[GitHub].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router that has problems with DNS-SRV records, review xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* The https://forums.couchbase.com/c/scala-sdk/37[community forum] is a great source of help.
////
