= Install and Start Using the Node.js SDK with Couchbase Server
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase
:navtitle: Start Using the SDK

[abstract]
The Couchbase Node.js SDK enables you to interact with a Couchbase Server cluster from the Node.js language.

The Couchbase Node.js SDK 3.0 is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 6.5 as a xref:concept-docs:collections.adoc[developer preview]).
The 3.0 SDK also brings in `promises`, to reduce the complexity of asynchronous javascript in client applications, as well as extending the management APIs and bringing better debugging and logging options


// tag::prep[]

// end::prep[]

// tag::install[]

include::partial$beta-warning.adoc[]

== Installing the SDK

[source,javascript]
----
npm install couchbase
----

// end::install[]

Information on new features, fixes, known issues, as well as information on how to install older release versions is xref:project-docs:sdk-release-notes.adoc[in the release notes].

== Hello Couchbase

Now you have the Node.js client installed, try out the following:

[source,javascript]
----
var cluster = new couchbase.Cluster(
    'http://10.112.180.101:8091', {
        username: 'Administrator',
        password: 'password'});
----

Couchbase uses xref:6.5@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use more appropriate, restrictive settings, but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.

[source,javascript]
----
// get a bucket reference
var bucket = cluster.bucket('bucket-name');
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,javascript]
----
// get a collection reference
var collection = bucket.defaultCollection();
var myCollection = bucket.collection("my-collection");
----

The latest release, 6.5β, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to a specified _Collection_.
Here we will use the `DefaultCollection`, rather than a specific collection, but best practice would be to group your users into a single collection, groups into another, etc...

[source,javascript]
----
// upsert document
var upsertResult = await collection.upsert("my-document", {name: 'mike'});

// get document
var getResult = await collection.get("my-document");
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
// Now that you know the basics, you may wish to go straight to that page.
//-- or first see a complete worked example of using the Couchbase node.js client, our xref:sample-application.adoc[Travel Sample Application].

== Additional Resources

// The API reference is generated for each release and can be found xref:http://docs.couchbase.com/sdk-api/couchbase-node-client-3.0.0dp1/[here].

// xref:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Node.js SDK.
The Node.js SDK source code is available on https://github.com/couchbase/couchnode[GitHub].
